export type Pair = {
  fr: string;
  es: string;
  note?: string;
};

export type Family = {
  id: string;
  frEnd: string;
  esEnd: string;
  title: string;
  rule: string;
  caveat: string;
  pairs: Pair[];
};

export const families: Family[] = [
  {
    id: "tion",
    frEnd: "-tion",
    esEnd: "-ción",
    title: "nation → nación",
    rule: "La plupart des noms français en -tion deviennent -ción en espagnol. L’accent tombe sur le ó.",
    caveat: "question se dit souvent pregunta. acción garde le c. Pas tous les -tion du quotidien (maison n’a rien à voir).",
    pairs: [
      { fr: "nation", es: "nación" },
      { fr: "information", es: "información" },
      { fr: "conversation", es: "conversación" },
      { fr: "situation", es: "situación" },
      { fr: "station", es: "estación" },
      { fr: "attention", es: "atención" },
      { fr: "action", es: "acción" },
      { fr: "émotion", es: "emoción" },
      { fr: "relation", es: "relación" },
      { fr: "tradition", es: "tradición" },
      { fr: "solution", es: "solución" },
      { fr: "condition", es: "condición" },
      { fr: "production", es: "producción" },
      { fr: "direction", es: "dirección" },
      { fr: "collection", es: "colección" },
    ],
  },
  {
    id: "sion",
    frEnd: "-sion",
    esEnd: "-sión",
    title: "décision → decisión",
    rule: "Les noms en -sion passent souvent en -sión, avec l’accent sur le ó.",
    caveat: "télévision = televisión. mission = misión.",
    pairs: [
      { fr: "décision", es: "decisión" },
      { fr: "télévision", es: "televisión" },
      { fr: "passion", es: "pasión" },
      { fr: "mission", es: "misión" },
      { fr: "pression", es: "presión" },
      { fr: "expression", es: "expresión" },
      { fr: "impression", es: "impresión" },
      { fr: "version", es: "versión" },
      { fr: "occasion", es: "ocasión" },
      { fr: "conclusion", es: "conclusión" },
    ],
  },
  {
    id: "te",
    frEnd: "-té",
    esEnd: "-dad",
    title: "liberté → libertad",
    rule: "Beaucoup de noms abstraits en -té (du latin -tas) deviennent -dad.",
    caveat: "cité peut être ciudad. santé = salud (exception). été n’est pas un cousin.",
    pairs: [
      { fr: "liberté", es: "libertad" },
      { fr: "université", es: "universidad" },
      { fr: "possibilité", es: "posibilidad" },
      { fr: "responsabilité", es: "responsabilidad" },
      { fr: "réalité", es: "realidad" },
      { fr: "qualité", es: "calidad" },
      { fr: "quantité", es: "cantidad" },
      { fr: "électricité", es: "electricidad" },
      { fr: "société", es: "sociedad" },
      { fr: "autorité", es: "autoridad" },
      { fr: "capacité", es: "capacidad" },
      { fr: "activité", es: "actividad" },
    ],
  },
  {
    id: "ance",
    frEnd: "-ance",
    esEnd: "-ancia",
    title: "importance → importancia",
    rule: "Les noms en -ance deviennent souvent -ancia.",
    caveat: "chance n’est pas chancia : suerte. distance = distancia.",
    pairs: [
      { fr: "importance", es: "importancia" },
      { fr: "distance", es: "distancia" },
      { fr: "constance", es: "constancia" },
      { fr: "élégance", es: "elegancia" },
      { fr: "ignorance", es: "ignorancia" },
      { fr: "vigilance", es: "vigilancia" },
      { fr: "tolérance", es: "tolerancia" },
      { fr: "abondance", es: "abundancia" },
    ],
  },
  {
    id: "ence",
    frEnd: "-ence",
    esEnd: "-encia",
    title: "différence → diferencia",
    rule: "Les noms en -ence deviennent souvent -encia.",
    caveat: "agence = agencia. silence = silencio (pas -encia).",
    pairs: [
      { fr: "différence", es: "diferencia" },
      { fr: "expérience", es: "experiencia" },
      { fr: "présence", es: "presencia" },
      { fr: "absence", es: "ausencia" },
      { fr: "urgence", es: "urgencia" },
      { fr: "patience", es: "paciencia" },
      { fr: "conscience", es: "conciencia" },
      { fr: "intelligence", es: "inteligencia" },
      { fr: "conférence", es: "conferencia" },
      { fr: "indépendance", es: "independencia" },
    ],
  },
  {
    id: "mente",
    frEnd: "-ment (adverbe)",
    esEnd: "-mente",
    title: "rapidement → rápidamente",
    rule: "Si le français est un adverbe en -ment, l’espagnol met souvent -mente (et un accent sur la voyelle de l’adjectif).",
    caveat: "Ce n’est pas le -ment des noms (changement). vraiment = realmente / de verdad.",
    pairs: [
      { fr: "rapidement", es: "rápidamente" },
      { fr: "lentement", es: "lentamente" },
      { fr: "normalement", es: "normalmente" },
      { fr: "finalement", es: "finalmente" },
      { fr: "probablement", es: "probablemente" },
      { fr: "seulement", es: "solamente" },
      { fr: "directement", es: "directamente" },
      { fr: "clairement", es: "claramente" },
      { fr: "spécialement", es: "especialmente" },
      { fr: "généralement", es: "generalmente" },
    ],
  },
  {
    id: "miento",
    frEnd: "-ment (nom)",
    esEnd: "-miento",
    title: "mouvement → movimiento",
    rule: "Beaucoup de noms d’action en -ment deviennent -miento.",
    caveat: "changement = cambio. gouvernement = gobierno. appartement = piso / apartamento.",
    pairs: [
      { fr: "mouvement", es: "movimiento" },
      { fr: "sentiment", es: "sentimiento" },
      { fr: "moment", es: "momento", note: "ici -o, pas -miento" },
      { fr: "document", es: "documento" },
      { fr: "élément", es: "elemento" },
      { fr: "instrument", es: "instrumento" },
      { fr: "argument", es: "argumento" },
      { fr: "traitement", es: "tratamiento" },
      { fr: "pensée", es: "pensamiento" },
      { fr: "naissance", es: "nacimiento" },
    ],
  },
  {
    id: "ique",
    frEnd: "-ique",
    esEnd: "-ico / -ica",
    title: "économique → económico",
    rule: "Les adjectifs (et certains noms) en -ique deviennent -ico / -ica.",
    caveat: "musique = música. politique = política. Unique reste único.",
    pairs: [
      { fr: "économique", es: "económico" },
      { fr: "politique", es: "político" },
      { fr: "pratique", es: "práctico" },
      { fr: "classique", es: "clásico" },
      { fr: "public", es: "público" },
      { fr: "musique", es: "música" },
      { fr: "logique", es: "lógico" },
      { fr: "magique", es: "mágico" },
      { fr: "technique", es: "técnico" },
      { fr: "électrique", es: "eléctrico" },
    ],
  },
  {
    id: "aire",
    frEnd: "-aire",
    esEnd: "-ario / -aria",
    title: "nécessaire → necesario",
    rule: "Les mots en -aire deviennent souvent -ario / -aria.",
    caveat: "affaires n’est pas arios. militaire = militar (pas -ario).",
    pairs: [
      { fr: "nécessaire", es: "necesario" },
      { fr: "ordinaire", es: "ordinario" },
      { fr: "dictionnaire", es: "diccionario" },
      { fr: "vocabulaire", es: "vocabulario" },
      { fr: "anniversaire", es: "aniversario" },
      { fr: "contraire", es: "contrario" },
      { fr: "solitaire", es: "solitario" },
      { fr: "volontaire", es: "voluntario" },
      { fr: "salarié", es: "asalariado" },
    ],
  },
  {
    id: "eur",
    frEnd: "-eur (personne)",
    esEnd: "-or",
    title: "acteur → actor",
    rule: "Beaucoup de métiers / agents en -eur deviennent -or.",
    caveat: "couleur = color. chaleur = calor. bonheur n’est pas bonor (felicidad). moteur = motor.",
    pairs: [
      { fr: "acteur", es: "actor" },
      { fr: "docteur", es: "doctor" },
      { fr: "professeur", es: "profesor" },
      { fr: "auteur", es: "autor" },
      { fr: "directeur", es: "director" },
      { fr: "moteur", es: "motor" },
      { fr: "couleur", es: "color" },
      { fr: "chaleur", es: "calor" },
      { fr: "horreur", es: "horror" },
      { fr: "honneur", es: "honor" },
    ],
  },
  {
    id: "eux",
    frEnd: "-eux / -euse",
    esEnd: "-oso / -osa",
    title: "généreux → generoso",
    rule: "Les adjectifs en -eux / -euse deviennent souvent -oso / -osa.",
    caveat: "heureux = feliz (pas felicioso). nerveux = nervioso.",
    pairs: [
      { fr: "généreux", es: "generoso" },
      { fr: "nerveux", es: "nervioso" },
      { fr: "curieux", es: "curioso" },
      { fr: "furieux", es: "furioso" },
      { fr: "délicieux", es: "delicioso" },
      { fr: "religieux", es: "religioso" },
      { fr: "ambitieux", es: "ambicioso" },
      { fr: "précieux", es: "precioso" },
      { fr: "mystérieux", es: "misterioso" },
    ],
  },
  {
    id: "iste",
    frEnd: "-iste",
    esEnd: "-ista",
    title: "artiste → artista",
    rule: "-iste reste presque identique : -ista (même forme au masculin et au féminin).",
    caveat: "liste n’est pas lista dans le même sens (lista = maligne / liste). cycliste = ciclista.",
    pairs: [
      { fr: "artiste", es: "artista" },
      { fr: "touriste", es: "turista" },
      { fr: "pianiste", es: "pianista" },
      { fr: "journaliste", es: "periodista", note: "exception de racine" },
      { fr: "cycliste", es: "ciclista" },
      { fr: "dentiste", es: "dentista" },
      { fr: "idéaliste", es: "idealista" },
      { fr: "réaliste", es: "realista" },
    ],
  },
  {
    id: "isme",
    frEnd: "-isme",
    esEnd: "-ismo",
    title: "tourisme → turismo",
    rule: "-isme devient -ismo.",
    caveat: "Peu d’exceptions. tourisme perd le ou : turismo.",
    pairs: [
      { fr: "tourisme", es: "turismo" },
      { fr: "organisme", es: "organismo" },
      { fr: "optimisme", es: "optimismo" },
      { fr: "pessimisme", es: "pesimismo" },
      { fr: "réalisme", es: "realismo" },
      { fr: "capitalisme", es: "capitalismo" },
      { fr: "mécanisme", es: "mecanismo" },
      { fr: "journalisme", es: "periodismo" },
    ],
  },
  {
    id: "ure",
    frEnd: "-ure",
    esEnd: "-ura",
    title: "culture → cultura",
    rule: "Les noms en -ure deviennent souvent -ura.",
    caveat: "voiture = coche / carro. blessure = herida.",
    pairs: [
      { fr: "culture", es: "cultura" },
      { fr: "nature", es: "naturaleza", note: "un peu plus long" },
      { fr: "littérature", es: "literatura" },
      { fr: "température", es: "temperatura" },
      { fr: "ouverture", es: "apertura" },
      { fr: "signature", es: "firma", note: "exception" },
      { fr: "structure", es: "estructura" },
      { fr: "aventure", es: "aventura" },
    ],
  },
  {
    id: "ble",
    frEnd: "-able / -ible",
    esEnd: "-able / -ible",
    title: "possible → posible",
    rule: "La terminaison reste presque la même. On perd souvent un s ou un accent français.",
    caveat: "table n’est pas un cousin de este type (mesa). aimable = amable.",
    pairs: [
      { fr: "possible", es: "posible" },
      { fr: "impossible", es: "imposible" },
      { fr: "probable", es: "probable" },
      { fr: "responsable", es: "responsable" },
      { fr: "confortable", es: "cómodo", note: "on dit plutôt cómodo que confortable" },
      { fr: "terrible", es: "terrible" },
      { fr: "visible", es: "visible" },
      { fr: "incroyable", es: "increíble" },
      { fr: "agréable", es: "agradable" },
    ],
  },
  {
    id: "al",
    frEnd: "-al / -el",
    esEnd: "-al",
    title: "national → nacional",
    rule: "Beaucoup d’adjectifs en -al restent -al. Ceux en -el (personnel) passent souvent en -al.",
    caveat: "mal n’est pas un cousin ici. journal = periódico.",
    pairs: [
      { fr: "national", es: "nacional" },
      { fr: "international", es: "internacional" },
      { fr: "normal", es: "normal" },
      { fr: "final", es: "final" },
      { fr: "personnel", es: "personal" },
      { fr: "professionnel", es: "profesional" },
      { fr: "officiel", es: "oficial" },
      { fr: "spécial", es: "especial" },
      { fr: "social", es: "social" },
      { fr: "local", es: "local" },
    ],
  },
  {
    id: "ph",
    frEnd: "ph / th",
    esEnd: "f / t",
    title: "photo → foto",
    rule: "L’espagnol n’aime pas ph et th : ph → f, th → t. Les mots restent reconnaissables.",
    caveat: "Ce n’est pas une terminaison, c’est l’orthographe. téléphone = teléfono.",
    pairs: [
      { fr: "photo", es: "foto" },
      { fr: "téléphone", es: "teléfono" },
      { fr: "philosophie", es: "filosofía" },
      { fr: "physique", es: "física" },
      { fr: "théâtre", es: "teatro" },
      { fr: "théorie", es: "teoría" },
      { fr: "athlète", es: "atleta" },
      { fr: "rythme", es: "ritmo" },
      { fr: "cathédrale", es: "catedral" },
    ],
  },
];

export const falseFriends: Pair[] = [
  { fr: "actuellement", es: "ahora", note: "actualmente veut plutôt dire « en ce moment / de nos jours », pas « en ce moment-ci » comme une horloge." },
  { fr: "large", es: "ancho", note: "largo = long" },
  { fr: "succès", es: "éxito", note: "suceso = un événement" },
  { fr: "embarrassé", es: "avergonzado", note: "embarazada = enceinte" },
  { fr: "constipé", es: "estreñido", note: "constipado = enrhumé" },
];

export function getFamily(id: string) {
  return families.find((family) => family.id === id);
}

export function allPairs() {
  return families.flatMap((family) =>
    family.pairs.filter((pair) => !pair.note?.startsWith("exception")).map((pair) => ({ ...pair, familyId: family.id })),
  );
}
