import type { DayLesson } from "./types";

export const THEME_LABEL: Record<DayLesson["theme"], string> = {
  quotidien: "Quotidien",
  foot: "Foot",
  voyage: "Souvenirs de voyage",
};

export const curriculum: DayLesson[] = [
  {
    day: 1,
    theme: "quotidien",
    title: "Hola, Amigo",
    goal: "Saluer Amigo et demander comment ça va.",
    amigoOpens: "¡Hola! ¿Qué tal?",
    amigoOpensFr: "Salut ! Ça va ?",
    phrases: [
      { es: "Hola, Amigo", fr: "Salut, Amigo" },
      { es: "¿Qué tal?", fr: "Ça va ?" },
      { es: "Bien, ¿y tú?", fr: "Bien, et toi ?" },
      { es: "Muy bien", fr: "Très bien" },
      { es: "Un poco cansado", fr: "Un peu fatigué" },
    ],
    drills: [
      { promptFr: "Salue Amigo.", sample: "Hola, Amigo", expect: ["hola", "amigo"] },
      { promptFr: "Demande-lui comment il va.", sample: "¿Qué tal?", expect: ["que tal"] },
      { promptFr: "Dis que tu vas bien, et toi ?", sample: "Bien, ¿y tú?", expect: ["bien", "tu"] },
    ],
  },
  {
    day: 2,
    theme: "quotidien",
    title: "Café de la mañana",
    goal: "Parler du café et du matin.",
    amigoOpens: "¿Quieres un café?",
    amigoOpensFr: "Tu veux un café ?",
    phrases: [
      { es: "Sí, por favor", fr: "Oui, s’il te plaît" },
      { es: "Un café, por favor", fr: "Un café, s’il te plaît" },
      { es: "Estoy cansado", fr: "Je suis fatigué" },
      { es: "Esta mañana", fr: "Ce matin" },
      { es: "Gracias, Amigo", fr: "Merci, Amigo" },
    ],
    drills: [
      { promptFr: "Dis oui, s’il te plaît.", sample: "Sí, por favor", expect: ["si", "favor"] },
      { promptFr: "Commande un café.", sample: "Un café, por favor", expect: ["cafe"] },
      { promptFr: "Dis que tu es fatigué.", sample: "Estoy cansado", expect: ["cansado"] },
    ],
  },
  {
    day: 3,
    theme: "quotidien",
    title: "¿Qué haces hoy?",
    goal: "Parler de ta journée.",
    amigoOpens: "¿Qué haces hoy?",
    amigoOpensFr: "Tu fais quoi aujourd’hui ?",
    phrases: [
      { es: "Hoy trabajo", fr: "Aujourd’hui je travaille" },
      { es: "Hoy descanso", fr: "Aujourd’hui je me repose" },
      { es: "Más tarde", fr: "Plus tard" },
      { es: "No lo sé", fr: "Je ne sais pas" },
      { es: "¿Y tú?", fr: "Et toi ?" },
    ],
    drills: [
      { promptFr: "Dis que tu travailles aujourd’hui.", sample: "Hoy trabajo", expect: ["hoy", "trabajo"] },
      { promptFr: "Dis que tu ne sais pas.", sample: "No lo sé", expect: ["no", "se"] },
      { promptFr: "Renvoie la question : et toi ?", sample: "¿Y tú?", expect: ["tu"] },
    ],
  },
  {
    day: 4,
    theme: "quotidien",
    title: "El tiempo",
    goal: "Dire le temps qu’il fait.",
    amigoOpens: "Hace mucho calor hoy.",
    amigoOpensFr: "Il fait très chaud aujourd’hui.",
    phrases: [
      { es: "Hace calor", fr: "Il fait chaud" },
      { es: "Hace frío", fr: "Il fait froid" },
      { es: "Llueve", fr: "Il pleut" },
      { es: "Hace buen tiempo", fr: "Il fait beau" },
      { es: "Prefiero el sol", fr: "Je préfère le soleil" },
    ],
    drills: [
      { promptFr: "Dis qu’il fait chaud.", sample: "Hace calor", expect: ["hace", "calor"] },
      { promptFr: "Dis qu’il pleut.", sample: "Llueve", expect: ["llueve"] },
      { promptFr: "Dis que tu préfères le soleil.", sample: "Prefiero el sol", expect: ["sol"] },
    ],
  },
  {
    day: 5,
    theme: "quotidien",
    title: "Tengo hambre",
    goal: "Parler de faim, soif, manger.",
    amigoOpens: "¿Tienes hambre?",
    amigoOpensFr: "Tu as faim ?",
    phrases: [
      { es: "Tengo hambre", fr: "J’ai faim" },
      { es: "Tengo sed", fr: "J’ai soif" },
      { es: "Vamos a comer", fr: "On va manger" },
      { es: "Está muy bueno", fr: "C’est très bon" },
      { es: "Yo también", fr: "Moi aussi" },
    ],
    drills: [
      { promptFr: "Dis que tu as faim.", sample: "Tengo hambre", expect: ["tengo", "hambre"] },
      { promptFr: "Propose d’aller manger.", sample: "Vamos a comer", expect: ["vamos", "comer"] },
      { promptFr: "Dis moi aussi.", sample: "Yo también", expect: ["tambien"] },
    ],
  },
  {
    day: 6,
    theme: "quotidien",
    title: "Por la noche",
    goal: "Parler du soir et des plans.",
    amigoOpens: "¿Qué hacemos esta noche?",
    amigoOpensFr: "On fait quoi ce soir ?",
    phrases: [
      { es: "Esta noche", fr: "Ce soir" },
      { es: "Estoy cansado", fr: "Je suis fatigué" },
      { es: "Podemos hablar", fr: "On peut parler" },
      { es: "Mañana", fr: "Demain" },
      { es: "Hasta luego", fr: "À plus tard" },
    ],
    drills: [
      { promptFr: "Dis ce soir.", sample: "Esta noche", expect: ["noche"] },
      { promptFr: "Propose de parler.", sample: "Podemos hablar", expect: ["hablar"] },
      { promptFr: "Dis à plus tard.", sample: "Hasta luego", expect: ["hasta", "luego"] },
    ],
  },
  {
    day: 7,
    theme: "quotidien",
    title: "La semana",
    goal: "Relier les jours et une petite semaine.",
    amigoOpens: "¿Cómo fue tu semana?",
    amigoOpensFr: "Comment était ta semaine ?",
    phrases: [
      { es: "Fue bien", fr: "C’était bien" },
      { es: "Fue dura", fr: "C’était dure" },
      { es: "El lunes", fr: "Lundi" },
      { es: "El fin de semana", fr: "Le week-end" },
      { es: "Necesito descansar", fr: "J’ai besoin de me reposer" },
    ],
    drills: [
      { promptFr: "Dis que c’était bien.", sample: "Fue bien", expect: ["fue", "bien"] },
      { promptFr: "Parle du week-end.", sample: "El fin de semana", expect: ["fin", "semana"] },
      { promptFr: "Dis que tu as besoin de te reposer.", sample: "Necesito descansar", expect: ["descansar"] },
    ],
  },
  {
    day: 8,
    theme: "foot",
    title: "¿Te gusta el fútbol?",
    goal: "Dire que tu aimes le foot.",
    amigoOpens: "¿Te gusta el fútbol?",
    amigoOpensFr: "Tu aimes le foot ?",
    phrases: [
      { es: "Me gusta el fútbol", fr: "J’aime le foot" },
      { es: "Me encanta", fr: "J’adore" },
      { es: "Un poco", fr: "Un peu" },
      { es: "¿Cuál es tu equipo?", fr: "C’est quoi ton équipe ?" },
      { es: "No mucho", fr: "Pas trop" },
    ],
    drills: [
      { promptFr: "Dis que tu aimes le foot.", sample: "Me gusta el fútbol", expect: ["gusta", "futbol"] },
      { promptFr: "Dis que tu adores.", sample: "Me encanta", expect: ["encanta"] },
      { promptFr: "Demande son équipe.", sample: "¿Cuál es tu equipo?", expect: ["equipo"] },
    ],
  },
  {
    day: 9,
    theme: "foot",
    title: "Mi equipo",
    goal: "Parler d’une équipe, sans jargon.",
    amigoOpens: "Mi equipo es el Barça. ¿Y el tuyo?",
    amigoOpensFr: "Mon équipe c’est le Barça. Et la tienne ?",
    phrases: [
      { es: "Mi equipo es...", fr: "Mon équipe c’est..." },
      { es: "No tengo un equipo", fr: "Je n’ai pas d’équipe" },
      { es: "Juegan bien", fr: "Ils jouent bien" },
      { es: "Hoy hay partido", fr: "Il y a un match aujourd’hui" },
      { es: "Vamos a verlo", fr: "On va le regarder" },
    ],
    drills: [
      { promptFr: "Dis que tu n’as pas d’équipe.", sample: "No tengo un equipo", expect: ["equipo"] },
      { promptFr: "Dis qu’il y a un match aujourd’hui.", sample: "Hoy hay partido", expect: ["partido"] },
      { promptFr: "Propose de le regarder.", sample: "Vamos a verlo", expect: ["vamos", "ver"] },
    ],
  },
  {
    day: 10,
    theme: "foot",
    title: "El partido",
    goal: "Commenter un match simplement.",
    amigoOpens: "¡Gol! ¿Lo viste?",
    amigoOpensFr: "But ! Tu l’as vu ?",
    phrases: [
      { es: "¡Qué gol!", fr: "Quel but !" },
      { es: "No lo vi", fr: "Je ne l’ai pas vu" },
      { es: "Estuvo cerca", fr: "C’était proche" },
      { es: "Ganamos", fr: "On a gagné" },
      { es: "Perdimos", fr: "On a perdu" },
    ],
    drills: [
      { promptFr: "Crie quel but !", sample: "¡Qué gol!", expect: ["gol"] },
      { promptFr: "Dis que tu n’as pas vu.", sample: "No lo vi", expect: ["no", "vi"] },
      { promptFr: "Dis qu’on a gagné.", sample: "Ganamos", expect: ["ganamos"] },
    ],
  },
  {
    day: 11,
    theme: "foot",
    title: "El fin de semana",
    goal: "Raconter le week-end foot.",
    amigoOpens: "El sábado vi el partido. Fue loco.",
    amigoOpensFr: "Samedi j’ai vu le match. C’était dingue.",
    phrases: [
      { es: "El sábado", fr: "Samedi" },
      { es: "Vi el partido", fr: "J’ai vu le match" },
      { es: "Fue loco", fr: "C’était dingue" },
      { es: "Con amigos", fr: "Avec des amis" },
      { es: "La próxima vez", fr: "La prochaine fois" },
    ],
    drills: [
      { promptFr: "Dis samedi.", sample: "El sábado", expect: ["sabado"] },
      { promptFr: "Dis que tu as vu le match.", sample: "Vi el partido", expect: ["vi", "partido"] },
      { promptFr: "Dis avec des amis.", sample: "Con amigos", expect: ["amigos"] },
    ],
  },
  {
    day: 12,
    theme: "foot",
    title: "Jugar un poco",
    goal: "Parler de jouer, pas seulement regarder.",
    amigoOpens: "¿Jugamos un poco este finde?",
    amigoOpensFr: "On joue un peu ce week-end ?",
    phrases: [
      { es: "Sí, vamos", fr: "Oui, allez" },
      { es: "No puedo", fr: "Je ne peux pas" },
      { es: "Juego un poco", fr: "Je joue un peu" },
      { es: "Soy malo", fr: "Je suis mauvais" },
      { es: "Da igual, es divertido", fr: "Peu importe, c’est marrant" },
    ],
    drills: [
      { promptFr: "Dis oui, allez.", sample: "Sí, vamos", expect: ["vamos"] },
      { promptFr: "Dis que tu ne peux pas.", sample: "No puedo", expect: ["puedo"] },
      { promptFr: "Dis que c’est marrant.", sample: "Es divertido", expect: ["divertido"] },
    ],
  },
  {
    day: 13,
    theme: "foot",
    title: "Tu jugador",
    goal: "Parler d’un joueur, simplement.",
    amigoOpens: "¿Quién es tu jugador favorito?",
    amigoOpensFr: "C’est qui ton joueur préféré ?",
    phrases: [
      { es: "No lo sé", fr: "Je ne sais pas" },
      { es: "Me gusta cómo juega", fr: "J’aime comme il joue" },
      { es: "Es muy rápido", fr: "Il est très rapide" },
      { es: "Es un buen equipo", fr: "C’est une bonne équipe" },
      { es: "¿Y el tuyo?", fr: "Et le tien ?" },
    ],
    drills: [
      { promptFr: "Dis que tu aimes comme il joue.", sample: "Me gusta cómo juega", expect: ["gusta", "juega"] },
      { promptFr: "Dis qu’il est très rapide.", sample: "Es muy rápido", expect: ["rapido"] },
      { promptFr: "Demande et le tien ?", sample: "¿Y el tuyo?", expect: ["tuyo"] },
    ],
  },
  {
    day: 14,
    theme: "foot",
    title: "Después del partido",
    goal: "Réagir après un match avec Amigo.",
    amigoOpens: "Menuda rabia. Merecíamos más.",
    amigoOpensFr: "Quelle rage. On méritait plus.",
    phrases: [
      { es: "Es así", fr: "C’est comme ça" },
      { es: "La próxima vez", fr: "La prochaine fois" },
      { es: "No pasa nada", fr: "C’est pas grave" },
      { es: "Fue un buen partido", fr: "C’était un bon match" },
      { es: "Hablamos luego", fr: "On se parle après" },
    ],
    drills: [
      { promptFr: "Dis que ce n’est pas grave.", sample: "No pasa nada", expect: ["pasa", "nada"] },
      { promptFr: "Dis que c’était un bon match.", sample: "Fue un buen partido", expect: ["buen", "partido"] },
      { promptFr: "Dis la prochaine fois.", sample: "La próxima vez", expect: ["proxima"] },
    ],
  },
  {
    day: 15,
    theme: "voyage",
    title: "Un recuerdo",
    goal: "Ouvrir un souvenir de voyage.",
    amigoOpens: "¿Cuál es tu mejor recuerdo de viaje?",
    amigoOpensFr: "C’est quoi ton meilleur souvenir de voyage ?",
    phrases: [
      { es: "Un viaje a...", fr: "Un voyage à..." },
      { es: "Hace unos años", fr: "Il y a quelques années" },
      { es: "Fue increíble", fr: "C’était incroyable" },
      { es: "No me acuerdo bien", fr: "Je ne me souviens pas bien" },
      { es: "Te lo cuento", fr: "Je te raconte" },
    ],
    drills: [
      { promptFr: "Dis que c’était incroyable.", sample: "Fue increíble", expect: ["increible"] },
      { promptFr: "Dis il y a quelques années.", sample: "Hace unos años", expect: ["anos"] },
      { promptFr: "Dis je te raconte.", sample: "Te lo cuento", expect: ["cuento"] },
    ],
  },
  {
    day: 16,
    theme: "voyage",
    title: "La carretera",
    goal: "Parler de la route et du van.",
    amigoOpens: "A mí me encanta la carretera.",
    amigoOpensFr: "Moi j’adore la route.",
    phrases: [
      { es: "El van", fr: "Le van" },
      { es: "En la carretera", fr: "Sur la route" },
      { es: "Dormimos allí", fr: "On a dormi là-bas" },
      { es: "Fue largo", fr: "C’était long" },
      { es: "Pero bonito", fr: "Mais joli" },
    ],
    drills: [
      { promptFr: "Dis sur la route.", sample: "En la carretera", expect: ["carretera"] },
      { promptFr: "Dis que c’était long.", sample: "Fue largo", expect: ["largo"] },
      { promptFr: "Dis mais joli.", sample: "Pero bonito", expect: ["bonito"] },
    ],
  },
  {
    day: 17,
    theme: "voyage",
    title: "La playa y la montaña",
    goal: "Choisir mer ou montagne.",
    amigoOpens: "¿Playa o montaña?",
    amigoOpensFr: "Plage ou montagne ?",
    phrases: [
      { es: "Prefiero la playa", fr: "Je préfère la plage" },
      { es: "Prefiero la montaña", fr: "Je préfère la montagne" },
      { es: "El mar estaba frío", fr: "La mer était froide" },
      { es: "Había mucha gente", fr: "Il y avait beaucoup de monde" },
      { es: "Estaba tranquilo", fr: "C’était calme" },
    ],
    drills: [
      { promptFr: "Dis que tu préfères la plage.", sample: "Prefiero la playa", expect: ["playa"] },
      { promptFr: "Dis qu’il y avait beaucoup de monde.", sample: "Había mucha gente", expect: ["gente"] },
      { promptFr: "Dis que c’était calme.", sample: "Estaba tranquilo", expect: ["tranquilo"] },
    ],
  },
  {
    day: 18,
    theme: "voyage",
    title: "Comida del viaje",
    goal: "Raconter un repas en voyage.",
    amigoOpens: "¿Qué comiste de camino?",
    amigoOpensFr: "Tu as mangé quoi sur la route ?",
    phrases: [
      { es: "Comimos allí", fr: "On a mangé là-bas" },
      { es: "Estaba muy bueno", fr: "C’était très bon" },
      { es: "Era barato", fr: "C’était pas cher" },
      { es: "No me gustó", fr: "Je n’ai pas aimé" },
      { es: "Quiero volver", fr: "Je veux y retourner" },
    ],
    drills: [
      { promptFr: "Dis que c’était très bon.", sample: "Estaba muy bueno", expect: ["bueno"] },
      { promptFr: "Dis que tu n’as pas aimé.", sample: "No me gustó", expect: ["gusto"] },
      { promptFr: "Dis que tu veux y retourner.", sample: "Quiero volver", expect: ["volver"] },
    ],
  },
  {
    day: 19,
    theme: "voyage",
    title: "Un problema",
    goal: "Raconter un petit galère de voyage.",
    amigoOpens: "Una vez se nos rompió el coche.",
    amigoOpensFr: "Une fois la voiture est tombée en panne.",
    phrases: [
      { es: "Tuvimos un problema", fr: "On a eu un problème" },
      { es: "No pasaba nada", fr: "Ce n’était pas grave" },
      { es: "Pedimos ayuda", fr: "On a demandé de l’aide" },
      { es: "Al final, bien", fr: "Au final, ça allait" },
      { es: "Fue una historia", fr: "C’était toute une histoire" },
    ],
    drills: [
      { promptFr: "Dis qu’on a eu un problème.", sample: "Tuvimos un problema", expect: ["problema"] },
      { promptFr: "Dis qu’on a demandé de l’aide.", sample: "Pedimos ayuda", expect: ["ayuda"] },
      { promptFr: "Dis au final, ça allait.", sample: "Al final, bien", expect: ["final"] },
    ],
  },
  {
    day: 20,
    theme: "voyage",
    title: "Gente del camino",
    goal: "Parler des gens croisés.",
    amigoOpens: "En la carretera conoces a mucha gente.",
    amigoOpensFr: "Sur la route tu croises plein de gens.",
    phrases: [
      { es: "Conocimos a gente", fr: "On a rencontré des gens" },
      { es: "Eran muy amables", fr: "Ils étaient très gentils" },
      { es: "Hablamos un poco", fr: "On a un peu parlé" },
      { es: "No hablaba español", fr: "Je ne parlais pas espagnol" },
      { es: "Igual nos entendimos", fr: "On s’est compris quand même" },
    ],
    drills: [
      { promptFr: "Dis qu’ils étaient très gentils.", sample: "Eran muy amables", expect: ["amables"] },
      { promptFr: "Dis qu’on a un peu parlé.", sample: "Hablamos un poco", expect: ["hablamos"] },
      { promptFr: "Dis qu’on s’est compris quand même.", sample: "Igual nos entendimos", expect: ["entendimos"] },
    ],
  },
  {
    day: 21,
    theme: "voyage",
    title: "El próximo viaje",
    goal: "Parler du prochain voyage.",
    amigoOpens: "¿Dónde quieres ir ahora?",
    amigoOpensFr: "Tu veux aller où maintenant ?",
    phrases: [
      { es: "Quiero ir a España", fr: "Je veux aller en Espagne" },
      { es: "Cuando pueda", fr: "Quand je pourrai" },
      { es: "Contigo", fr: "Avec toi" },
      { es: "Todavía no lo sé", fr: "Je ne sais pas encore" },
      { es: "Pronto, espero", fr: "Bientôt, j’espère" },
    ],
    drills: [
      { promptFr: "Dis que tu veux aller en Espagne.", sample: "Quiero ir a España", expect: ["espana"] },
      { promptFr: "Dis avec toi.", sample: "Contigo", expect: ["contigo"] },
      { promptFr: "Dis bientôt, j’espère.", sample: "Pronto, espero", expect: ["pronto"] },
    ],
  },
  {
    day: 22,
    theme: "quotidien",
    title: "¿Cómo estás de verdad?",
    goal: "Dire comment tu vas vraiment.",
    amigoOpens: "¿Cómo estás de verdad?",
    amigoOpensFr: "Comment tu vas, vraiment ?",
    phrases: [
      { es: "Estoy bien, de verdad", fr: "Je vais bien, vraiment" },
      { es: "Estoy regular", fr: "Comme ci comme ça" },
      { es: "Estoy un poco triste", fr: "Je suis un peu triste" },
      { es: "Estoy contento", fr: "Je suis content" },
      { es: "Gracias por preguntar", fr: "Merci de demander" },
    ],
    drills: [
      { promptFr: "Dis comme ci comme ça.", sample: "Estoy regular", expect: ["regular"] },
      { promptFr: "Dis que tu es content.", sample: "Estoy contento", expect: ["contento"] },
      { promptFr: "Remercie-le d’avoir demandé.", sample: "Gracias por preguntar", expect: ["gracias"] },
    ],
  },
  {
    day: 23,
    theme: "foot",
    title: "Antes del partido",
    goal: "Parler avant un match.",
    amigoOpens: "Esta noche hay partido. Estoy nervioso.",
    amigoOpensFr: "Ce soir il y a match. Je suis nerveux.",
    phrases: [
      { es: "Yo también", fr: "Moi aussi" },
      { es: "Vamos a ganar", fr: "On va gagner" },
      { es: "A ver qué pasa", fr: "On verra ce qui se passe" },
      { es: "¿A qué hora es?", fr: "C’est à quelle heure ?" },
      { es: "Te escribo luego", fr: "Je t’écris après" },
    ],
    drills: [
      { promptFr: "Dis on va gagner.", sample: "Vamos a ganar", expect: ["ganar"] },
      { promptFr: "Demande à quelle heure.", sample: "¿A qué hora es?", expect: ["hora"] },
      { promptFr: "Dis je t’écris après.", sample: "Te escribo luego", expect: ["luego"] },
    ],
  },
  {
    day: 24,
    theme: "voyage",
    title: "Una foto",
    goal: "Parler d’une photo de voyage.",
    amigoOpens: "Mira esta foto. ¿Te acuerdas?",
    amigoOpensFr: "Regarde cette photo. Tu te souviens ?",
    phrases: [
      { es: "Sí, me acuerdo", fr: "Oui, je me souviens" },
      { es: "¿Dónde era?", fr: "C’était où ?" },
      { es: "Qué bueno", fr: "Trop bien" },
      { es: "Ese día fue especial", fr: "Ce jour-là était spécial" },
      { es: "Mándame más", fr: "Envoie-m’en d’autres" },
    ],
    drills: [
      { promptFr: "Dis que tu te souviens.", sample: "Sí, me acuerdo", expect: ["acuerdo"] },
      { promptFr: "Demande c’était où.", sample: "¿Dónde era?", expect: ["donde"] },
      { promptFr: "Dis que ce jour était spécial.", sample: "Ese día fue especial", expect: ["especial"] },
    ],
  },
  {
    day: 25,
    theme: "quotidien",
    title: "Planes juntos",
    goal: "Proposer un plan simple.",
    amigoOpens: "¿Quedamos un día de estos?",
    amigoOpensFr: "On se voit un de ces jours ?",
    phrases: [
      { es: "Sí, claro", fr: "Oui, bien sûr" },
      { es: "¿Cuándo?", fr: "Quand ?" },
      { es: "El sábado está bien", fr: "Samedi ça me va" },
      { es: "Puedo por la tarde", fr: "Je peux l’après-midi" },
      { es: "Perfecto", fr: "Parfait" },
    ],
    drills: [
      { promptFr: "Dis oui, bien sûr.", sample: "Sí, claro", expect: ["claro"] },
      { promptFr: "Demande quand.", sample: "¿Cuándo?", expect: ["cuando"] },
      { promptFr: "Dis samedi ça me va.", sample: "El sábado está bien", expect: ["sabado"] },
    ],
  },
  {
    day: 26,
    theme: "foot",
    title: "Opinión suave",
    goal: "Donner un avis simple sur le jeu.",
    amigoOpens: "Para mí, jugaron mal el segundo tiempo.",
    amigoOpensFr: "Pour moi, ils ont mal joué en seconde période.",
    phrases: [
      { es: "Para mí...", fr: "Pour moi..." },
      { es: "Estoy de acuerdo", fr: "Je suis d’accord" },
      { es: "No estoy de acuerdo", fr: "Je ne suis pas d’accord" },
      { es: "Más o menos", fr: "Plus ou moins" },
      { es: "Hay que ver el próximo", fr: "Il faut voir le prochain" },
    ],
    drills: [
      { promptFr: "Dis que tu es d’accord.", sample: "Estoy de acuerdo", expect: ["acuerdo"] },
      { promptFr: "Dis que tu n’es pas d’accord.", sample: "No estoy de acuerdo", expect: ["no", "acuerdo"] },
      { promptFr: "Dis plus ou moins.", sample: "Más o menos", expect: ["menos"] },
    ],
  },
  {
    day: 27,
    theme: "voyage",
    title: "Lo que extraño",
    goal: "Dire ce qui te manque d’un voyage.",
    amigoOpens: "A veces extraño aquellos días.",
    amigoOpensFr: "Parfois ces jours-là me manquent.",
    phrases: [
      { es: "Yo también", fr: "Moi aussi" },
      { es: "Extraño la carretera", fr: "La route me manque" },
      { es: "Extraño esos días", fr: "Ces jours-là me manquent" },
      { es: "Fue un buen tiempo", fr: "C’était une belle période" },
      { es: "Volveremos", fr: "On y retournera" },
    ],
    drills: [
      { promptFr: "Dis que la route te manque.", sample: "Extraño la carretera", expect: ["extrano"] },
      { promptFr: "Dis que c’était une belle période.", sample: "Fue un buen tiempo", expect: ["buen", "tiempo"] },
      { promptFr: "Dis on y retournera.", sample: "Volveremos", expect: ["volveremos"] },
    ],
  },
  {
    day: 28,
    theme: "quotidien",
    title: "Una llamada corta",
    goal: "Tenir un mini-appel du quotidien.",
    amigoOpens: "Oye, ¿tienes un minuto?",
    amigoOpensFr: "Dis, tu as une minute ?",
    phrases: [
      { es: "Sí, dime", fr: "Oui, dis-moi" },
      { es: "Ahora no puedo", fr: "Là je ne peux pas" },
      { es: "Te llamo luego", fr: "Je t’appelle après" },
      { es: "Estoy ocupado", fr: "Je suis occupé" },
      { es: "Cuéntame", fr: "Raconte" },
    ],
    drills: [
      { promptFr: "Dis oui, dis-moi.", sample: "Sí, dime", expect: ["dime"] },
      { promptFr: "Dis que tu l’appelles après.", sample: "Te llamo luego", expect: ["llamo"] },
      { promptFr: "Dis raconte.", sample: "Cuéntame", expect: ["cuentame"] },
    ],
  },
  {
    day: 29,
    theme: "foot",
    title: "Llamada de partido",
    goal: "Enchaîner quotidien + foot dans un appel.",
    amigoOpens: "¿Viste el partido o estabas trabajando?",
    amigoOpensFr: "Tu as vu le match ou tu travaillais ?",
    phrases: [
      { es: "Estaba trabajando", fr: "Je travaillais" },
      { es: "Vi un poco", fr: "J’en ai vu un peu" },
      { es: "¿Quién ganó?", fr: "Qui a gagné ?" },
      { es: "Luego lo veo", fr: "Je le regarde après" },
      { es: "Cuéntame el final", fr: "Raconte-moi la fin" },
    ],
    drills: [
      { promptFr: "Dis que tu travaillais.", sample: "Estaba trabajando", expect: ["trabajando"] },
      { promptFr: "Demande qui a gagné.", sample: "¿Quién ganó?", expect: ["gano"] },
      { promptFr: "Demande-lui de raconter la fin.", sample: "Cuéntame el final", expect: ["final"] },
    ],
  },
  {
    day: 30,
    theme: "voyage",
    title: "Hablar con Amigo",
    goal: "Tenir 3 minutes : quotidien, foot, un souvenir.",
    amigoOpens: "Bueno. Hoy hablamos de todo. ¿Cómo estás?",
    amigoOpensFr: "Allez. Aujourd’hui on parle de tout. Comment tu vas ?",
    phrases: [
      { es: "Estoy bien, ¿y tú?", fr: "Je vais bien, et toi ?" },
      { es: "Ayer vi el partido", fr: "Hier j’ai vu le match" },
      { es: "Me acordé de un viaje", fr: "Je me suis souvenu d’un voyage" },
      { es: "Fue un buen día", fr: "C’était une bonne journée" },
      { es: "Hablamos pronto", fr: "On se parle bientôt" },
    ],
    drills: [
      { promptFr: "Dis que tu vas bien, et toi ?", sample: "Estoy bien, ¿y tú?", expect: ["bien", "tu"] },
      { promptFr: "Dis qu’hier tu as vu le match.", sample: "Ayer vi el partido", expect: ["ayer", "partido"] },
      { promptFr: "Dis on se parle bientôt.", sample: "Hablamos pronto", expect: ["pronto"] },
    ],
  },
];

export function getLesson(day: number) {
  return curriculum.find((item) => item.day === day) ?? curriculum[0];
}

export function todaySuggestedDay(completed: number[]) {
  for (let day = 1; day <= 30; day += 1) {
    if (!completed.includes(day)) return day;
  }
  return 30;
}
