export type Word500 = {
  id: string;
  fr: string;
  es: string;
  alt?: string[];
};

export const WORDS_500: Word500[] = [
  { id: "1", fr: "salut / bonjour (informel)", es: "hola" },
  { id: "2", fr: "bonjour (matin)", es: "buenos días" },
  { id: "3", fr: "bonjour (après-midi)", es: "buenas tardes" },
  { id: "4", fr: "bonsoir", es: "buenas noches" },
  { id: "5", fr: "au revoir", es: "adiós" },
  { id: "6", fr: "à plus tard", es: "hasta luego" },
  { id: "7", fr: "à demain", es: "hasta mañana" },
  { id: "8", fr: "s’il te plaît", es: "por favor" },
  { id: "9", fr: "merci", es: "gracias" },
  { id: "10", fr: "de rien", es: "de nada" },
  { id: "11", fr: "pardon", es: "perdón" },
  { id: "12", fr: "je suis désolé", es: "lo siento" },
  { id: "13", fr: "excuse-moi (passer)", es: "con permiso" },
  { id: "14", fr: "enchanté", es: "encantado" },
  { id: "15", fr: "bienvenue", es: "bienvenido" },
  { id: "16", fr: "ça va ?", es: "qué tal" },
  { id: "17", fr: "comment tu vas ?", es: "cómo estás" },
  { id: "18", fr: "bien", es: "bien" },
  { id: "19", fr: "mal", es: "mal" },
  { id: "20", fr: "comme ci comme ça", es: "regular" },
  { id: "21", fr: "plus ou moins", es: "más o menos" },
  { id: "22", fr: "d’accord / OK", es: "vale" },
  { id: "23", fr: "bien sûr", es: "claro" },
  { id: "24", fr: "oui", es: "sí" },
  { id: "25", fr: "non", es: "no" },
  { id: "26", fr: "je", es: "yo" },
  { id: "27", fr: "tu", es: "tú" },
  { id: "28", fr: "il", es: "él" },
  { id: "29", fr: "elle", es: "ella" },
  { id: "30", fr: "nous", es: "nosotros" },
  { id: "31", fr: "vous (pluriel Espagne)", es: "vosotros" },
  { id: "32", fr: "ils", es: "ellos" },
  { id: "33", fr: "elles", es: "ellas" },
  { id: "34", fr: "me / moi (complément)", es: "me" },
  { id: "35", fr: "te / toi (complément)", es: "te" },
  { id: "36", fr: "se (réfléchi)", es: "se" },
  { id: "37", fr: "nous (complément)", es: "nos" },
  { id: "38", fr: "mon / ma", es: "mi" },
  { id: "39", fr: "son / sa", es: "su" },
  { id: "40", fr: "ceci", es: "esto" },
  { id: "41", fr: "cela", es: "eso" },
  { id: "42", fr: "cela (loin)", es: "aquello" },
  { id: "43", fr: "la", es: "la" },
  { id: "44", fr: "les (masc.)", es: "los" },
  { id: "45", fr: "les (fém.)", es: "las" },
  { id: "46", fr: "un", es: "un" },
  { id: "47", fr: "une", es: "una" },
  { id: "48", fr: "de", es: "de" },
  { id: "49", fr: "à", es: "a" },
  { id: "50", fr: "en / dans", es: "en" },
  { id: "51", fr: "avec", es: "con" },
  { id: "52", fr: "par / pour (durée, cause)", es: "por" },
  { id: "53", fr: "pour (but, destinataire)", es: "para" },
  { id: "54", fr: "sans", es: "sin" },
  { id: "55", fr: "sur", es: "sobre" },
  { id: "56", fr: "entre", es: "entre" },
  { id: "57", fr: "jusqu’à", es: "hasta" },
  { id: "58", fr: "depuis", es: "desde" },
  { id: "59", fr: "vers", es: "hacia" },
  { id: "60", fr: "contre", es: "contra" },
  { id: "61", fr: "quoi / que", es: "qué" },
  { id: "62", fr: "qui", es: "quién" },
  { id: "63", fr: "où", es: "dónde" },
  { id: "64", fr: "quand", es: "cuándo" },
  { id: "65", fr: "comment", es: "cómo" },
  { id: "66", fr: "combien", es: "cuánto" },
  { id: "67", fr: "quel / lequel", es: "cuál" },
  { id: "68", fr: "pourquoi", es: "por qué" },
  { id: "69", fr: "parce que", es: "porque" },
  { id: "70", fr: "ou", es: "o" },
  { id: "71", fr: "et", es: "y" },
  { id: "72", fr: "mais", es: "pero" },
  { id: "73", fr: "aussi", es: "también" },
  { id: "74", fr: "non plus", es: "tampoco" },
  { id: "75", fr: "être (essence)", es: "ser" },
  { id: "76", fr: "être (état)", es: "estar" },
  { id: "77", fr: "avoir (auxiliaire / il y a)", es: "haber" },
  { id: "78", fr: "avoir (posséder)", es: "tener" },
  { id: "79", fr: "faire", es: "hacer" },
  { id: "80", fr: "pouvoir", es: "poder" },
  { id: "81", fr: "dire", es: "decir" },
  { id: "82", fr: "aller", es: "ir" },
  { id: "83", fr: "voir", es: "ver" },
  { id: "84", fr: "donner", es: "dar" },
  { id: "85", fr: "savoir", es: "saber" },
  { id: "86", fr: "vouloir", es: "querer" },
  { id: "87", fr: "arriver", es: "llegar" },
  { id: "88", fr: "passer", es: "pasar" },
  { id: "89", fr: "devoir", es: "deber" },
  { id: "90", fr: "mettre", es: "poner" },
  { id: "91", fr: "paraître / sembler", es: "parecer" },
  { id: "92", fr: "rester / se trouver", es: "quedar" },
  { id: "93", fr: "parler", es: "hablar" },
  { id: "94", fr: "porter / emmener", es: "llevar" },
  { id: "95", fr: "laisser", es: "dejar" },
  { id: "96", fr: "suivre / continuer", es: "seguir" },
  { id: "97", fr: "trouver", es: "encontrar" },
  { id: "98", fr: "appeler", es: "llamar" },
  { id: "99", fr: "venir", es: "venir" },
  { id: "100", fr: "penser", es: "pensar" },
  { id: "101", fr: "sortir", es: "salir" },
  { id: "102", fr: "revenir", es: "volver" },
  { id: "103", fr: "prendre", es: "tomar" },
  { id: "104", fr: "connaître", es: "conocer" },
  { id: "105", fr: "vivre", es: "vivir" },
  { id: "106", fr: "sentir", es: "sentir" },
  { id: "107", fr: "regarder", es: "mirar" },
  { id: "108", fr: "raconter / compter", es: "contar" },
  { id: "109", fr: "commencer", es: "empezar" },
  { id: "110", fr: "attendre / espérer", es: "esperar" },
  { id: "111", fr: "chercher", es: "buscar" },
  { id: "112", fr: "exister", es: "existir" },
  { id: "113", fr: "entrer", es: "entrar" },
  { id: "114", fr: "travailler", es: "trabajar" },
  { id: "115", fr: "écrire", es: "escribir" },
  { id: "116", fr: "perdre", es: "perder" },
  { id: "117", fr: "comprendre", es: "entender" },
  { id: "118", fr: "demander (réclamer)", es: "pedir" },
  { id: "119", fr: "recevoir", es: "recibir" },
  { id: "120", fr: "se souvenir", es: "recordar" },
  { id: "121", fr: "finir", es: "terminar" },
  { id: "122", fr: "permettre", es: "permitir" },
  { id: "123", fr: "apparaître", es: "aparecer" },
  { id: "124", fr: "obtenir", es: "conseguir" },
  { id: "125", fr: "ouvrir", es: "abrir" },
  { id: "126", fr: "fermer", es: "cerrar" },
  { id: "127", fr: "gagner", es: "ganar" },
  { id: "128", fr: "apporter", es: "traer" },
  { id: "129", fr: "partir", es: "partir" },
  { id: "130", fr: "accepter", es: "aceptar" },
  { id: "131", fr: "expliquer", es: "explicar" },
  { id: "132", fr: "poser une question", es: "preguntar" },
  { id: "133", fr: "étudier", es: "estudiar" },
  { id: "134", fr: "courir", es: "correr" },
  { id: "135", fr: "utiliser", es: "usar" },
  { id: "136", fr: "payer", es: "pagar" },
  { id: "137", fr: "aider", es: "ayudar" },
  { id: "138", fr: "aimer (plaire)", es: "gustar" },
  { id: "139", fr: "avoir besoin", es: "necesitar" },
  { id: "140", fr: "croire", es: "creer" },
  { id: "141", fr: "jouer", es: "jugar" },
  { id: "142", fr: "manger", es: "comer" },
  { id: "143", fr: "boire", es: "beber" },
  { id: "144", fr: "dormir", es: "dormir" },
  { id: "145", fr: "se réveiller", es: "despertar" },
  { id: "146", fr: "marcher", es: "caminar" },
  { id: "147", fr: "voyager", es: "viajar" },
  { id: "148", fr: "acheter", es: "comprar" },
  { id: "149", fr: "vendre", es: "vender" },
  { id: "150", fr: "changer", es: "cambiar" },
  { id: "151", fr: "écouter", es: "escuchar" },
  { id: "152", fr: "lire", es: "leer" },
  { id: "153", fr: "chanter", es: "cantar" },
  { id: "154", fr: "danser", es: "bailar" },
  { id: "155", fr: "cuisiner", es: "cocinar" },
  { id: "156", fr: "nettoyer", es: "limpiar" },
  { id: "157", fr: "conduire", es: "conducir" },
  { id: "158", fr: "oublier", es: "olvidar" },
  { id: "159", fr: "apprendre", es: "aprender" },
  { id: "160", fr: "enseigner", es: "enseñar" },
  { id: "161", fr: "essayer", es: "probar" },
  { id: "162", fr: "rester", es: "quedarse" },
  { id: "163", fr: "s’asseoir", es: "sentarse" },
  { id: "164", fr: "se lever", es: "levantarse" },
  { id: "165", fr: "je suis (essence)", es: "soy" },
  { id: "166", fr: "tu es (essence)", es: "eres" },
  { id: "167", fr: "il/elle est (essence)", es: "es" },
  { id: "168", fr: "nous sommes", es: "somos" },
  { id: "169", fr: "je suis (état)", es: "estoy" },
  { id: "170", fr: "tu es (état)", es: "estás" },
  { id: "171", fr: "il/elle est (état)", es: "está" },
  { id: "172", fr: "j’ai", es: "tengo" },
  { id: "173", fr: "tu as", es: "tienes" },
  { id: "174", fr: "il/elle a", es: "tiene" },
  { id: "175", fr: "il y a", es: "hay" },
  { id: "176", fr: "je vais", es: "voy" },
  { id: "177", fr: "tu vas", es: "vas" },
  { id: "178", fr: "il/elle va", es: "va" },
  { id: "179", fr: "on y va / nous allons", es: "vamos" },
  { id: "180", fr: "je veux", es: "quiero" },
  { id: "181", fr: "tu veux", es: "quieres" },
  { id: "182", fr: "je peux", es: "puedo" },
  { id: "183", fr: "il/elle peut", es: "puede" },
  { id: "184", fr: "je fais", es: "hago" },
  { id: "185", fr: "il/elle fait", es: "hace" },
  { id: "186", fr: "il/elle dit", es: "dice" },
  { id: "187", fr: "c’était", es: "fue" },
  { id: "188", fr: "il fallait / j’avais", es: "tenía" },
  { id: "189", fr: "j’étais (état)", es: "estaba" },
  { id: "190", fr: "il y a (obligation)", es: "hay que" },
  { id: "191", fr: "je dois / il faut que j’aie", es: "tengo que" },
  { id: "192", fr: "ça me plaît", es: "me gusta" },
  { id: "193", fr: "aujourd’hui", es: "hoy" },
  { id: "194", fr: "hier", es: "ayer" },
  { id: "195", fr: "demain", es: "mañana" },
  { id: "196", fr: "maintenant", es: "ahora" },
  { id: "197", fr: "ensuite", es: "luego" },
  { id: "198", fr: "après", es: "después" },
  { id: "199", fr: "avant", es: "antes" },
  { id: "200", fr: "toujours", es: "siempre" },
  { id: "201", fr: "jamais", es: "nunca" },
  { id: "202", fr: "parfois", es: "a veces" },
  { id: "203", fr: "déjà", es: "ya" },
  { id: "204", fr: "encore / toujours (durée)", es: "todavía" },
  { id: "205", fr: "tôt", es: "temprano" },
  { id: "206", fr: "tard", es: "tarde" },
  { id: "207", fr: "bientôt", es: "pronto" },
  { id: "208", fr: "moment", es: "momento" },
  { id: "209", fr: "heure", es: "hora" },
  { id: "210", fr: "minute", es: "minuto" },
  { id: "211", fr: "jour", es: "día" },
  { id: "212", fr: "semaine", es: "semana" },
  { id: "213", fr: "mois", es: "mes" },
  { id: "214", fr: "année", es: "año" },
  { id: "215", fr: "lundi", es: "lunes" },
  { id: "216", fr: "mardi", es: "martes" },
  { id: "217", fr: "mercredi", es: "miércoles" },
  { id: "218", fr: "jeudi", es: "jueves" },
  { id: "219", fr: "vendredi", es: "viernes" },
  { id: "220", fr: "samedi", es: "sábado" },
  { id: "221", fr: "dimanche", es: "domingo" },
  { id: "222", fr: "week-end", es: "fin de semana" },
  { id: "223", fr: "nuit", es: "noche" },
  { id: "224", fr: "matin", es: "mañana", alt: ["mañana"] },
  { id: "225", fr: "zéro", es: "cero" },
  { id: "226", fr: "un (nombre)", es: "uno" },
  { id: "227", fr: "deux", es: "dos" },
  { id: "228", fr: "trois", es: "tres" },
  { id: "229", fr: "quatre", es: "cuatro" },
  { id: "230", fr: "cinq", es: "cinco" },
  { id: "231", fr: "six", es: "seis" },
  { id: "232", fr: "sept", es: "siete" },
  { id: "233", fr: "huit", es: "ocho" },
  { id: "234", fr: "neuf", es: "nueve" },
  { id: "235", fr: "dix", es: "diez" },
  { id: "236", fr: "onze", es: "once" },
  { id: "237", fr: "douze", es: "doce" },
  { id: "238", fr: "vingt", es: "veinte" },
  { id: "239", fr: "trente", es: "treinta" },
  { id: "240", fr: "cent", es: "cien" },
  { id: "241", fr: "mille", es: "mil" },
  { id: "242", fr: "premier", es: "primero" },
  { id: "243", fr: "dernier", es: "último" },
  { id: "244", fr: "beaucoup", es: "mucho" },
  { id: "245", fr: "peu", es: "poco" },
  { id: "246", fr: "plus", es: "más" },
  { id: "247", fr: "moins", es: "menos" },
  { id: "248", fr: "tout", es: "todo" },
  { id: "249", fr: "rien", es: "nada" },
  { id: "250", fr: "homme", es: "hombre" },
  { id: "251", fr: "femme", es: "mujer" },
  { id: "252", fr: "personne", es: "persona" },
  { id: "253", fr: "gens", es: "gente" },
  { id: "254", fr: "ami", es: "amigo" },
  { id: "255", fr: "amie", es: "amiga" },
  { id: "256", fr: "famille", es: "familia" },
  { id: "257", fr: "père", es: "padre" },
  { id: "258", fr: "mère", es: "madre" },
  { id: "259", fr: "fils", es: "hijo" },
  { id: "260", fr: "fille (enfant)", es: "hija" },
  { id: "261", fr: "frère", es: "hermano" },
  { id: "262", fr: "sœur", es: "hermana" },
  { id: "263", fr: "enfant (garçon)", es: "niño" },
  { id: "264", fr: "enfant (fille)", es: "niña" },
  { id: "265", fr: "garçon", es: "chico" },
  { id: "266", fr: "fille (jeune)", es: "chica" },
  { id: "267", fr: "monsieur", es: "señor" },
  { id: "268", fr: "madame", es: "señora" },
  { id: "269", fr: "nom", es: "nombre" },
  { id: "270", fr: "vie", es: "vida" },
  { id: "271", fr: "amour", es: "amor" },
  { id: "272", fr: "main", es: "mano" },
  { id: "273", fr: "tête", es: "cabeza" },
  { id: "274", fr: "œil", es: "ojo" },
  { id: "275", fr: "corps", es: "cuerpo" },
  { id: "276", fr: "cœur", es: "corazón" },
  { id: "277", fr: "fatigué", es: "cansado" },
  { id: "278", fr: "heureux / content", es: "feliz" },
  { id: "279", fr: "triste", es: "triste" },
  { id: "280", fr: "malade", es: "enfermo" },
  { id: "281", fr: "faim", es: "hambre" },
  { id: "282", fr: "soif", es: "sed" },
  { id: "283", fr: "froid", es: "frío" },
  { id: "284", fr: "chaleur / chaud", es: "calor" },
  { id: "285", fr: "peur", es: "miedo" },
  { id: "286", fr: "douleur", es: "dolor" },
  { id: "287", fr: "maison", es: "casa" },
  { id: "288", fr: "porte", es: "puerta" },
  { id: "289", fr: "fenêtre", es: "ventana" },
  { id: "290", fr: "table", es: "mesa" },
  { id: "291", fr: "chaise", es: "silla" },
  { id: "292", fr: "lit", es: "cama" },
  { id: "293", fr: "eau", es: "agua" },
  { id: "294", fr: "lumière", es: "luz" },
  { id: "295", fr: "chambre", es: "habitación" },
  { id: "296", fr: "salle de bain", es: "baño" },
  { id: "297", fr: "cuisine", es: "cocina" },
  { id: "298", fr: "rue", es: "calle" },
  { id: "299", fr: "ville", es: "ciudad" },
  { id: "300", fr: "village", es: "pueblo" },
  { id: "301", fr: "pays", es: "país" },
  { id: "302", fr: "monde", es: "mundo" },
  { id: "303", fr: "lieu", es: "lugar" },
  { id: "304", fr: "ici", es: "aquí" },
  { id: "305", fr: "là-bas", es: "allí" },
  { id: "306", fr: "nourriture / repas", es: "comida" },
  { id: "307", fr: "petit-déjeuner", es: "desayuno" },
  { id: "308", fr: "déjeuner", es: "almuerzo" },
  { id: "309", fr: "dîner", es: "cena" },
  { id: "310", fr: "pain", es: "pan" },
  { id: "311", fr: "lait", es: "leche" },
  { id: "312", fr: "café", es: "café" },
  { id: "313", fr: "bière", es: "cerveza" },
  { id: "314", fr: "vin", es: "vino" },
  { id: "315", fr: "viande", es: "carne" },
  { id: "316", fr: "poisson", es: "pescado" },
  { id: "317", fr: "fruit", es: "fruta" },
  { id: "318", fr: "légume", es: "verdura" },
  { id: "319", fr: "riz", es: "arroz" },
  { id: "320", fr: "œuf", es: "huevo" },
  { id: "321", fr: "fromage", es: "queso" },
  { id: "322", fr: "sucre", es: "azúcar" },
  { id: "323", fr: "sel", es: "sal" },
  { id: "324", fr: "restaurant", es: "restaurante" },
  { id: "325", fr: "addition", es: "cuenta" },
  { id: "326", fr: "assiette", es: "plato" },
  { id: "327", fr: "verre", es: "vaso" },
  { id: "328", fr: "voyage", es: "viaje" },
  { id: "329", fr: "voiture", es: "coche" },
  { id: "330", fr: "train", es: "tren" },
  { id: "331", fr: "avion", es: "avión" },
  { id: "332", fr: "bus", es: "autobús" },
  { id: "333", fr: "gare", es: "estación" },
  { id: "334", fr: "aéroport", es: "aeropuerto" },
  { id: "335", fr: "hôtel", es: "hotel" },
  { id: "336", fr: "valise", es: "maleta" },
  { id: "337", fr: "carte / plan", es: "mapa" },
  { id: "338", fr: "chemin", es: "camino" },
  { id: "339", fr: "route", es: "carretera" },
  { id: "340", fr: "plage", es: "playa" },
  { id: "341", fr: "mer", es: "mar" },
  { id: "342", fr: "montagne", es: "montaña" },
  { id: "343", fr: "rivière", es: "río" },
  { id: "344", fr: "forêt", es: "bosque" },
  { id: "345", fr: "parc", es: "parque" },
  { id: "346", fr: "billet", es: "billete" },
  { id: "347", fr: "passeport", es: "pasaporte" },
  { id: "348", fr: "van", es: "van" },
  { id: "349", fr: "essence", es: "gasolina" },
  { id: "350", fr: "football", es: "fútbol" },
  { id: "351", fr: "match", es: "partido" },
  { id: "352", fr: "équipe", es: "equipo" },
  { id: "353", fr: "but (foot)", es: "gol" },
  { id: "354", fr: "joueur", es: "jugador" },
  { id: "355", fr: "ballon", es: "pelota" },
  { id: "356", fr: "terrain", es: "campo" },
  { id: "357", fr: "bon", es: "bueno" },
  { id: "358", fr: "mauvais", es: "malo" },
  { id: "359", fr: "grand", es: "grande" },
  { id: "360", fr: "petit", es: "pequeño" },
  { id: "361", fr: "nouveau", es: "nuevo" },
  { id: "362", fr: "vieux", es: "viejo" },
  { id: "363", fr: "jeune", es: "joven" },
  { id: "364", fr: "joli / beau", es: "bonito" },
  { id: "365", fr: "facile", es: "fácil" },
  { id: "366", fr: "difficile", es: "difícil" },
  { id: "367", fr: "important", es: "importante" },
  { id: "368", fr: "possible", es: "posible" },
  { id: "369", fr: "même", es: "mismo" },
  { id: "370", fr: "autre", es: "otro" },
  { id: "371", fr: "meilleur", es: "mejor" },
  { id: "372", fr: "pire", es: "peor" },
  { id: "373", fr: "rapide", es: "rápido" },
  { id: "374", fr: "lent", es: "lento" },
  { id: "375", fr: "près", es: "cerca" },
  { id: "376", fr: "loin", es: "lejos" },
  { id: "377", fr: "plein", es: "lleno" },
  { id: "378", fr: "vide", es: "vacío" },
  { id: "379", fr: "ouvert", es: "abierto" },
  { id: "380", fr: "fermé", es: "cerrado" },
  { id: "381", fr: "propre", es: "limpio" },
  { id: "382", fr: "sale", es: "sucio" },
  { id: "383", fr: "cher", es: "caro" },
  { id: "384", fr: "pas cher", es: "barato" },
  { id: "385", fr: "haut", es: "alto" },
  { id: "386", fr: "bas", es: "bajo" },
  { id: "387", fr: "long", es: "largo" },
  { id: "388", fr: "court", es: "corto" },
  { id: "389", fr: "fort", es: "fuerte" },
  { id: "390", fr: "libre", es: "libre" },
  { id: "391", fr: "occupé", es: "ocupado" },
  { id: "392", fr: "prêt", es: "listo" },
  { id: "393", fr: "seul", es: "solo" },
  { id: "394", fr: "très", es: "muy" },
  { id: "395", fr: "assez", es: "bastante" },
  { id: "396", fr: "trop", es: "demasiado" },
  { id: "397", fr: "ainsi", es: "así" },
  { id: "398", fr: "alors", es: "entonces" },
  { id: "399", fr: "en plus", es: "además" },
  { id: "400", fr: "bien que", es: "aunque" },
  { id: "401", fr: "pendant que", es: "mientras" },
  { id: "402", fr: "pendant", es: "durante" },
  { id: "403", fr: "presque", es: "casi" },
  { id: "404", fr: "seulement", es: "solamente" },
  { id: "405", fr: "vraiment", es: "realmente" },
  { id: "406", fr: "peut-être", es: "quizás" },
  { id: "407", fr: "pourvu que", es: "ojalá" },
  { id: "408", fr: "travail", es: "trabajo" },
  { id: "409", fr: "bureau", es: "oficina" },
  { id: "410", fr: "école", es: "escuela" },
  { id: "411", fr: "université", es: "universidad" },
  { id: "412", fr: "magasin", es: "tienda" },
  { id: "413", fr: "marché", es: "mercado" },
  { id: "414", fr: "banque", es: "banco" },
  { id: "415", fr: "hôpital", es: "hospital" },
  { id: "416", fr: "cinéma", es: "cine" },
  { id: "417", fr: "bar", es: "bar" },
  { id: "418", fr: "place (publique)", es: "plaza" },
  { id: "419", fr: "téléphone", es: "teléfono" },
  { id: "420", fr: "photo", es: "foto" },
  { id: "421", fr: "musique", es: "música" },
  { id: "422", fr: "film", es: "película" },
  { id: "423", fr: "livre", es: "libro" },
  { id: "424", fr: "mot", es: "palabra" },
  { id: "425", fr: "question", es: "pregunta" },
  { id: "426", fr: "réponse", es: "respuesta" },
  { id: "427", fr: "problème", es: "problema" },
  { id: "428", fr: "idée", es: "idea" },
  { id: "429", fr: "chose", es: "cosa" },
  { id: "430", fr: "partie", es: "parte" },
  { id: "431", fr: "exemple", es: "ejemplo" },
  { id: "432", fr: "numéro / nombre", es: "número" },
  { id: "433", fr: "couleur", es: "color" },
  { id: "434", fr: "argent", es: "dinero" },
  { id: "435", fr: "prix", es: "precio" },
  { id: "436", fr: "temps (météo ou durée)", es: "tiempo" },
  { id: "437", fr: "langue", es: "idioma" },
  { id: "438", fr: "espagnol", es: "español" },
  { id: "439", fr: "français", es: "francés" },
  { id: "440", fr: "anglais", es: "inglés" },
  { id: "441", fr: "je ne comprends pas", es: "no entiendo" },
  { id: "442", fr: "tu peux répéter ?", es: "puedes repetir" },
  { id: "443", fr: "plus lentement", es: "más despacio" },
  { id: "444", fr: "comment on dit", es: "cómo se dice" },
  { id: "445", fr: "je ne sais pas", es: "no sé" },
  { id: "446", fr: "je ne peux pas", es: "no puedo" },
  { id: "447", fr: "bien sûr que oui", es: "claro que sí" },
  { id: "448", fr: "ce n’est pas grave", es: "no pasa nada" },
  { id: "449", fr: "à tout à l’heure", es: "hasta ahora" },
  { id: "450", fr: "on se voit", es: "nos vemos" },
  { id: "451", fr: "je t’aime (ami)", es: "te quiero" },
  { id: "452", fr: "s’il vous plaît (formel déjà couvert)", es: "porfa", alt: ["por favor"] },
  { id: "453", fr: "d’accord (entendu)", es: "de acuerdo" },
  { id: "454", fr: "c’est ça", es: "eso es" },
  { id: "455", fr: "moi aussi", es: "yo también" },
  { id: "456", fr: "moi non plus", es: "yo tampoco" },
  { id: "457", fr: "qu’est-ce que c’est ?", es: "qué es esto" },
  { id: "458", fr: "où est", es: "dónde está" },
  { id: "459", fr: "combien ça coûte", es: "cuánto cuesta" },
  { id: "460", fr: "je voudrais", es: "quisiera" },
  { id: "461", fr: "aide-moi", es: "ayúdame" },
  { id: "462", fr: "regarde", es: "mira" },
  { id: "463", fr: "écoute", es: "escucha" },
  { id: "464", fr: "viens", es: "ven" },
  { id: "465", fr: "attends", es: "espera" },
  { id: "466", fr: "dis-moi", es: "dime" },
  { id: "467", fr: "raconte", es: "cuéntame" },
  { id: "468", fr: "je t’appelle", es: "te llamo" },
  { id: "469", fr: "je t’écris", es: "te escribo" },
  { id: "470", fr: "à bientôt", es: "hasta pronto" },
  { id: "471", fr: "bonne journée", es: "buen día" },
  { id: "472", fr: "santé (tchin)", es: "salud" },
  { id: "473", fr: "félicitations", es: "felicidades" },
  { id: "474", fr: "bonjour (très informel)", es: "hey" },
  { id: "475", fr: "mec / pote", es: "tío" },
  { id: "476", fr: "super / génial", es: "genial" },
  { id: "477", fr: "cool", es: "guay" },
  { id: "478", fr: "dingue", es: "loco" },
  { id: "479", fr: "vrai", es: "verdad" },
  { id: "480", fr: "mensonge", es: "mentira" },
  { id: "481", fr: "histoire", es: "historia" },
  { id: "482", fr: "souvenir", es: "recuerdo" },
  { id: "483", fr: "rêve", es: "sueño" },
  { id: "484", fr: "pluie", es: "lluvia" },
  { id: "485", fr: "soleil", es: "sol" },
  { id: "486", fr: "il fait beau", es: "hace buen tiempo" },
  { id: "487", fr: "il pleut", es: "llueve" },
  { id: "488", fr: "il fait chaud", es: "hace calor" },
  { id: "489", fr: "il fait froid", es: "hace frío" },
  { id: "490", fr: "vent", es: "viento" },
  { id: "491", fr: "ciel", es: "cielo" },
  { id: "492", fr: "terre", es: "tierra" },
  { id: "493", fr: "feu", es: "fuego" },
  { id: "494", fr: "chien", es: "perro" },
  { id: "495", fr: "chat", es: "gato" },
  { id: "496", fr: "animal", es: "animal" },
  { id: "497", fr: "arbre", es: "árbol" },
  { id: "498", fr: "fleur", es: "flor" },
  { id: "499", fr: "rouge", es: "rojo" },
  { id: "500", fr: "bleu", es: "azul" },
];

export const WORD_COUNT = WORDS_500.length;
