import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const raw = [
  { fr: "salut / bonjour (informel)", es: "hola" },
  { fr: "bonjour (matin)", es: "buenos días" },
  { fr: "bonjour (après-midi)", es: "buenas tardes" },
  { fr: "bonsoir", es: "buenas noches" },
  { fr: "au revoir", es: "adiós" },
  { fr: "à plus tard", es: "hasta luego" },
  { fr: "à demain", es: "hasta mañana" },
  { fr: "s’il te plaît", es: "por favor" },
  { fr: "merci", es: "gracias" },
  { fr: "de rien", es: "de nada" },
  { fr: "pardon", es: "perdón" },
  { fr: "je suis désolé", es: "lo siento" },
  { fr: "excuse-moi (passer)", es: "con permiso" },
  { fr: "enchanté", es: "encantado" },
  { fr: "bienvenue", es: "bienvenido" },
  { fr: "ça va ?", es: "qué tal" },
  { fr: "comment tu vas ?", es: "cómo estás" },
  { fr: "bien", es: "bien" },
  { fr: "mal", es: "mal" },
  { fr: "comme ci comme ça", es: "regular" },
  { fr: "plus ou moins", es: "más o menos" },
  { fr: "d’accord / OK", es: "vale" },
  { fr: "bien sûr", es: "claro" },
  { fr: "oui", es: "sí" },
  { fr: "non", es: "no" },
  { fr: "je", es: "yo" },
  { fr: "tu", es: "tú" },
  { fr: "il", es: "él" },
  { fr: "elle", es: "ella" },
  { fr: "nous", es: "nosotros" },
  { fr: "vous (pluriel Espagne)", es: "vosotros" },
  { fr: "ils", es: "ellos" },
  { fr: "elles", es: "ellas" },
  { fr: "me / moi (complément)", es: "me" },
  { fr: "te / toi (complément)", es: "te" },
  { fr: "se (réfléchi)", es: "se" },
  { fr: "nous (complément)", es: "nos" },
  { fr: "mon / ma", es: "mi" },
  { fr: "ton / ta", es: "tu" },
  { fr: "son / sa", es: "su" },
  { fr: "ceci", es: "esto" },
  { fr: "cela", es: "eso" },
  { fr: "cela (loin)", es: "aquello" },
  { fr: "le (article)", es: "el" },
  { fr: "la", es: "la" },
  { fr: "les (masc.)", es: "los" },
  { fr: "les (fém.)", es: "las" },
  { fr: "un", es: "un" },
  { fr: "une", es: "una" },
  { fr: "de", es: "de" },
  { fr: "à", es: "a" },
  { fr: "en / dans", es: "en" },
  { fr: "avec", es: "con" },
  { fr: "par / pour (durée, cause)", es: "por" },
  { fr: "pour (but, destinataire)", es: "para" },
  { fr: "sans", es: "sin" },
  { fr: "sur", es: "sobre" },
  { fr: "entre", es: "entre" },
  { fr: "jusqu’à", es: "hasta" },
  { fr: "depuis", es: "desde" },
  { fr: "vers", es: "hacia" },
  { fr: "contre", es: "contra" },
  { fr: "quoi / que", es: "qué" },
  { fr: "qui", es: "quién" },
  { fr: "où", es: "dónde" },
  { fr: "quand", es: "cuándo" },
  { fr: "comment", es: "cómo" },
  { fr: "combien", es: "cuánto" },
  { fr: "quel / lequel", es: "cuál" },
  { fr: "pourquoi", es: "por qué" },
  { fr: "parce que", es: "porque" },
  { fr: "si (condition)", es: "si" },
  { fr: "ou", es: "o" },
  { fr: "et", es: "y" },
  { fr: "mais", es: "pero" },
  { fr: "aussi", es: "también" },
  { fr: "non plus", es: "tampoco" },
  { fr: "être (essence)", es: "ser" },
  { fr: "être (état)", es: "estar" },
  { fr: "avoir (auxiliaire / il y a)", es: "haber" },
  { fr: "avoir (posséder)", es: "tener" },
  { fr: "faire", es: "hacer" },
  { fr: "pouvoir", es: "poder" },
  { fr: "dire", es: "decir" },
  { fr: "aller", es: "ir" },
  { fr: "voir", es: "ver" },
  { fr: "donner", es: "dar" },
  { fr: "savoir", es: "saber" },
  { fr: "vouloir", es: "querer" },
  { fr: "arriver", es: "llegar" },
  { fr: "passer", es: "pasar" },
  { fr: "devoir", es: "deber" },
  { fr: "mettre", es: "poner" },
  { fr: "paraître / sembler", es: "parecer" },
  { fr: "rester / se trouver", es: "quedar" },
  { fr: "parler", es: "hablar" },
  { fr: "porter / emmener", es: "llevar" },
  { fr: "laisser", es: "dejar" },
  { fr: "suivre / continuer", es: "seguir" },
  { fr: "trouver", es: "encontrar" },
  { fr: "appeler", es: "llamar" },
  { fr: "venir", es: "venir" },
  { fr: "penser", es: "pensar" },
  { fr: "sortir", es: "salir" },
  { fr: "revenir", es: "volver" },
  { fr: "prendre", es: "tomar" },
  { fr: "connaître", es: "conocer" },
  { fr: "vivre", es: "vivir" },
  { fr: "sentir", es: "sentir" },
  { fr: "regarder", es: "mirar" },
  { fr: "raconter / compter", es: "contar" },
  { fr: "commencer", es: "empezar" },
  { fr: "attendre / espérer", es: "esperar" },
  { fr: "chercher", es: "buscar" },
  { fr: "exister", es: "existir" },
  { fr: "entrer", es: "entrar" },
  { fr: "travailler", es: "trabajar" },
  { fr: "écrire", es: "escribir" },
  { fr: "perdre", es: "perder" },
  { fr: "comprendre", es: "entender" },
  { fr: "demander (réclamer)", es: "pedir" },
  { fr: "recevoir", es: "recibir" },
  { fr: "se souvenir", es: "recordar" },
  { fr: "finir", es: "terminar" },
  { fr: "permettre", es: "permitir" },
  { fr: "apparaître", es: "aparecer" },
  { fr: "obtenir", es: "conseguir" },
  { fr: "ouvrir", es: "abrir" },
  { fr: "fermer", es: "cerrar" },
  { fr: "gagner", es: "ganar" },
  { fr: "apporter", es: "traer" },
  { fr: "partir", es: "partir" },
  { fr: "accepter", es: "aceptar" },
  { fr: "expliquer", es: "explicar" },
  { fr: "poser une question", es: "preguntar" },
  { fr: "étudier", es: "estudiar" },
  { fr: "courir", es: "correr" },
  { fr: "utiliser", es: "usar" },
  { fr: "payer", es: "pagar" },
  { fr: "aider", es: "ayudar" },
  { fr: "aimer (plaire)", es: "gustar" },
  { fr: "avoir besoin", es: "necesitar" },
  { fr: "croire", es: "creer" },
  { fr: "jouer", es: "jugar" },
  { fr: "manger", es: "comer" },
  { fr: "boire", es: "beber" },
  { fr: "dormir", es: "dormir" },
  { fr: "se réveiller", es: "despertar" },
  { fr: "marcher", es: "caminar" },
  { fr: "voyager", es: "viajar" },
  { fr: "acheter", es: "comprar" },
  { fr: "vendre", es: "vender" },
  { fr: "changer", es: "cambiar" },
  { fr: "écouter", es: "escuchar" },
  { fr: "lire", es: "leer" },
  { fr: "chanter", es: "cantar" },
  { fr: "danser", es: "bailar" },
  { fr: "cuisiner", es: "cocinar" },
  { fr: "nettoyer", es: "limpiar" },
  { fr: "conduire", es: "conducir" },
  { fr: "oublier", es: "olvidar" },
  { fr: "apprendre", es: "aprender" },
  { fr: "enseigner", es: "enseñar" },
  { fr: "essayer", es: "probar" },
  { fr: "rester", es: "quedarse" },
  { fr: "s’asseoir", es: "sentarse" },
  { fr: "se lever", es: "levantarse" },
  { fr: "je suis (essence)", es: "soy" },
  { fr: "tu es (essence)", es: "eres" },
  { fr: "il/elle est (essence)", es: "es" },
  { fr: "nous sommes", es: "somos" },
  { fr: "je suis (état)", es: "estoy" },
  { fr: "tu es (état)", es: "estás" },
  { fr: "il/elle est (état)", es: "está" },
  { fr: "j’ai", es: "tengo" },
  { fr: "tu as", es: "tienes" },
  { fr: "il/elle a", es: "tiene" },
  { fr: "il y a", es: "hay" },
  { fr: "je vais", es: "voy" },
  { fr: "tu vas", es: "vas" },
  { fr: "il/elle va", es: "va" },
  { fr: "on y va / nous allons", es: "vamos" },
  { fr: "je veux", es: "quiero" },
  { fr: "tu veux", es: "quieres" },
  { fr: "je peux", es: "puedo" },
  { fr: "il/elle peut", es: "puede" },
  { fr: "je fais", es: "hago" },
  { fr: "il/elle fait", es: "hace" },
  { fr: "il/elle dit", es: "dice" },
  { fr: "je sais", es: "sé" },
  { fr: "c’était", es: "fue" },
  { fr: "il fallait / j’avais", es: "tenía" },
  { fr: "j’étais (état)", es: "estaba" },
  { fr: "il y a (obligation)", es: "hay que" },
  { fr: "je dois / il faut que j’aie", es: "tengo que" },
  { fr: "ça me plaît", es: "me gusta" },
  { fr: "aujourd’hui", es: "hoy" },
  { fr: "hier", es: "ayer" },
  { fr: "demain", es: "mañana" },
  { fr: "maintenant", es: "ahora" },
  { fr: "ensuite", es: "luego" },
  { fr: "après", es: "después" },
  { fr: "avant", es: "antes" },
  { fr: "toujours", es: "siempre" },
  { fr: "jamais", es: "nunca" },
  { fr: "parfois", es: "a veces" },
  { fr: "déjà", es: "ya" },
  { fr: "encore / toujours (durée)", es: "todavía" },
  { fr: "tôt", es: "temprano" },
  { fr: "tard", es: "tarde" },
  { fr: "bientôt", es: "pronto" },
  { fr: "moment", es: "momento" },
  { fr: "heure", es: "hora" },
  { fr: "minute", es: "minuto" },
  { fr: "jour", es: "día" },
  { fr: "semaine", es: "semana" },
  { fr: "mois", es: "mes" },
  { fr: "année", es: "año" },
  { fr: "lundi", es: "lunes" },
  { fr: "mardi", es: "martes" },
  { fr: "mercredi", es: "miércoles" },
  { fr: "jeudi", es: "jueves" },
  { fr: "vendredi", es: "viernes" },
  { fr: "samedi", es: "sábado" },
  { fr: "dimanche", es: "domingo" },
  { fr: "week-end", es: "fin de semana" },
  { fr: "nuit", es: "noche" },
  { fr: "matin", es: "mañana (por la)" , alt: ["mañana"] },
  { fr: "zéro", es: "cero" },
  { fr: "un (nombre)", es: "uno" },
  { fr: "deux", es: "dos" },
  { fr: "trois", es: "tres" },
  { fr: "quatre", es: "cuatro" },
  { fr: "cinq", es: "cinco" },
  { fr: "six", es: "seis" },
  { fr: "sept", es: "siete" },
  { fr: "huit", es: "ocho" },
  { fr: "neuf", es: "nueve" },
  { fr: "dix", es: "diez" },
  { fr: "onze", es: "once" },
  { fr: "douze", es: "doce" },
  { fr: "vingt", es: "veinte" },
  { fr: "trente", es: "treinta" },
  { fr: "cent", es: "cien" },
  { fr: "mille", es: "mil" },
  { fr: "premier", es: "primero" },
  { fr: "dernier", es: "último" },
  { fr: "beaucoup", es: "mucho" },
  { fr: "peu", es: "poco" },
  { fr: "plus", es: "más" },
  { fr: "moins", es: "menos" },
  { fr: "tout", es: "todo" },
  { fr: "rien", es: "nada" },
  { fr: "homme", es: "hombre" },
  { fr: "femme", es: "mujer" },
  { fr: "personne", es: "persona" },
  { fr: "gens", es: "gente" },
  { fr: "ami", es: "amigo" },
  { fr: "amie", es: "amiga" },
  { fr: "famille", es: "familia" },
  { fr: "père", es: "padre" },
  { fr: "mère", es: "madre" },
  { fr: "fils", es: "hijo" },
  { fr: "fille (enfant)", es: "hija" },
  { fr: "frère", es: "hermano" },
  { fr: "sœur", es: "hermana" },
  { fr: "enfant (garçon)", es: "niño" },
  { fr: "enfant (fille)", es: "niña" },
  { fr: "garçon", es: "chico" },
  { fr: "fille (jeune)", es: "chica" },
  { fr: "monsieur", es: "señor" },
  { fr: "madame", es: "señora" },
  { fr: "nom", es: "nombre" },
  { fr: "vie", es: "vida" },
  { fr: "amour", es: "amor" },
  { fr: "main", es: "mano" },
  { fr: "tête", es: "cabeza" },
  { fr: "œil", es: "ojo" },
  { fr: "corps", es: "cuerpo" },
  { fr: "cœur", es: "corazón" },
  { fr: "fatigué", es: "cansado" },
  { fr: "heureux / content", es: "feliz" },
  { fr: "triste", es: "triste" },
  { fr: "malade", es: "enfermo" },
  { fr: "faim", es: "hambre" },
  { fr: "soif", es: "sed" },
  { fr: "froid", es: "frío" },
  { fr: "chaleur / chaud", es: "calor" },
  { fr: "peur", es: "miedo" },
  { fr: "douleur", es: "dolor" },
  { fr: "maison", es: "casa" },
  { fr: "porte", es: "puerta" },
  { fr: "fenêtre", es: "ventana" },
  { fr: "table", es: "mesa" },
  { fr: "chaise", es: "silla" },
  { fr: "lit", es: "cama" },
  { fr: "eau", es: "agua" },
  { fr: "lumière", es: "luz" },
  { fr: "chambre", es: "habitación" },
  { fr: "salle de bain", es: "baño" },
  { fr: "cuisine", es: "cocina" },
  { fr: "rue", es: "calle" },
  { fr: "ville", es: "ciudad" },
  { fr: "village", es: "pueblo" },
  { fr: "pays", es: "país" },
  { fr: "monde", es: "mundo" },
  { fr: "lieu", es: "lugar" },
  { fr: "ici", es: "aquí" },
  { fr: "là-bas", es: "allí" },
  { fr: "nourriture / repas", es: "comida" },
  { fr: "petit-déjeuner", es: "desayuno" },
  { fr: "déjeuner", es: "almuerzo" },
  { fr: "dîner", es: "cena" },
  { fr: "pain", es: "pan" },
  { fr: "lait", es: "leche" },
  { fr: "café", es: "café" },
  { fr: "bière", es: "cerveza" },
  { fr: "vin", es: "vino" },
  { fr: "viande", es: "carne" },
  { fr: "poisson", es: "pescado" },
  { fr: "fruit", es: "fruta" },
  { fr: "légume", es: "verdura" },
  { fr: "riz", es: "arroz" },
  { fr: "œuf", es: "huevo" },
  { fr: "fromage", es: "queso" },
  { fr: "sucre", es: "azúcar" },
  { fr: "sel", es: "sal" },
  { fr: "restaurant", es: "restaurante" },
  { fr: "addition", es: "cuenta" },
  { fr: "assiette", es: "plato" },
  { fr: "verre", es: "vaso" },
  { fr: "voyage", es: "viaje" },
  { fr: "voiture", es: "coche" },
  { fr: "train", es: "tren" },
  { fr: "avion", es: "avión" },
  { fr: "bus", es: "autobús" },
  { fr: "gare", es: "estación" },
  { fr: "aéroport", es: "aeropuerto" },
  { fr: "hôtel", es: "hotel" },
  { fr: "valise", es: "maleta" },
  { fr: "carte / plan", es: "mapa" },
  { fr: "chemin", es: "camino" },
  { fr: "route", es: "carretera" },
  { fr: "plage", es: "playa" },
  { fr: "mer", es: "mar" },
  { fr: "montagne", es: "montaña" },
  { fr: "rivière", es: "río" },
  { fr: "forêt", es: "bosque" },
  { fr: "parc", es: "parque" },
  { fr: "billet", es: "billete" },
  { fr: "passeport", es: "pasaporte" },
  { fr: "van", es: "van" },
  { fr: "essence", es: "gasolina" },
  { fr: "football", es: "fútbol" },
  { fr: "match", es: "partido" },
  { fr: "équipe", es: "equipo" },
  { fr: "but (foot)", es: "gol" },
  { fr: "joueur", es: "jugador" },
  { fr: "ballon", es: "pelota" },
  { fr: "terrain", es: "campo" },
  { fr: "bon", es: "bueno" },
  { fr: "mauvais", es: "malo" },
  { fr: "grand", es: "grande" },
  { fr: "petit", es: "pequeño" },
  { fr: "nouveau", es: "nuevo" },
  { fr: "vieux", es: "viejo" },
  { fr: "jeune", es: "joven" },
  { fr: "joli / beau", es: "bonito" },
  { fr: "facile", es: "fácil" },
  { fr: "difficile", es: "difícil" },
  { fr: "important", es: "importante" },
  { fr: "possible", es: "posible" },
  { fr: "même", es: "mismo" },
  { fr: "autre", es: "otro" },
  { fr: "meilleur", es: "mejor" },
  { fr: "pire", es: "peor" },
  { fr: "rapide", es: "rápido" },
  { fr: "lent", es: "lento" },
  { fr: "près", es: "cerca" },
  { fr: "loin", es: "lejos" },
  { fr: "plein", es: "lleno" },
  { fr: "vide", es: "vacío" },
  { fr: "ouvert", es: "abierto" },
  { fr: "fermé", es: "cerrado" },
  { fr: "propre", es: "limpio" },
  { fr: "sale", es: "sucio" },
  { fr: "cher", es: "caro" },
  { fr: "pas cher", es: "barato" },
  { fr: "haut", es: "alto" },
  { fr: "bas", es: "bajo" },
  { fr: "long", es: "largo" },
  { fr: "court", es: "corto" },
  { fr: "fort", es: "fuerte" },
  { fr: "libre", es: "libre" },
  { fr: "occupé", es: "ocupado" },
  { fr: "prêt", es: "listo" },
  { fr: "seul", es: "solo" },
  { fr: "très", es: "muy" },
  { fr: "assez", es: "bastante" },
  { fr: "trop", es: "demasiado" },
  { fr: "ainsi", es: "así" },
  { fr: "alors", es: "entonces" },
  { fr: "en plus", es: "además" },
  { fr: "bien que", es: "aunque" },
  { fr: "pendant que", es: "mientras" },
  { fr: "pendant", es: "durante" },
  { fr: "presque", es: "casi" },
  { fr: "seulement", es: "solamente" },
  { fr: "vraiment", es: "realmente" },
  { fr: "peut-être", es: "quizás" },
  { fr: "pourvu que", es: "ojalá" },
  { fr: "travail", es: "trabajo" },
  { fr: "bureau", es: "oficina" },
  { fr: "école", es: "escuela" },
  { fr: "université", es: "universidad" },
  { fr: "magasin", es: "tienda" },
  { fr: "marché", es: "mercado" },
  { fr: "banque", es: "banco" },
  { fr: "hôpital", es: "hospital" },
  { fr: "cinéma", es: "cine" },
  { fr: "bar", es: "bar" },
  { fr: "place (publique)", es: "plaza" },
  { fr: "téléphone", es: "teléfono" },
  { fr: "photo", es: "foto" },
  { fr: "musique", es: "música" },
  { fr: "film", es: "película" },
  { fr: "livre", es: "libro" },
  { fr: "mot", es: "palabra" },
  { fr: "question", es: "pregunta" },
  { fr: "réponse", es: "respuesta" },
  { fr: "problème", es: "problema" },
  { fr: "idée", es: "idea" },
  { fr: "chose", es: "cosa" },
  { fr: "partie", es: "parte" },
  { fr: "exemple", es: "ejemplo" },
  { fr: "numéro / nombre", es: "número" },
  { fr: "couleur", es: "color" },
  { fr: "argent", es: "dinero" },
  { fr: "prix", es: "precio" },
  { fr: "temps (météo ou durée)", es: "tiempo" },
  { fr: "langue", es: "idioma" },
  { fr: "espagnol", es: "español" },
  { fr: "français", es: "francés" },
  { fr: "anglais", es: "inglés" },
  { fr: "je ne comprends pas", es: "no entiendo" },
  { fr: "tu peux répéter ?", es: "puedes repetir" },
  { fr: "plus lentement", es: "más despacio" },
  { fr: "comment on dit", es: "cómo se dice" },
  { fr: "je ne sais pas", es: "no sé" },
  { fr: "je ne peux pas", es: "no puedo" },
  { fr: "bien sûr que oui", es: "claro que sí" },
  { fr: "ce n’est pas grave", es: "no pasa nada" },
  { fr: "à tout à l’heure", es: "hasta ahora" },
  { fr: "on se voit", es: "nos vemos" },
  { fr: "je t’aime (ami)", es: "te quiero" },
  { fr: "s’il vous plaît (formel déjà couvert)", es: "porfa", alt: ["por favor"] },
  { fr: "d’accord (entendu)", es: "de acuerdo" },
  { fr: "c’est ça", es: "eso es" },
  { fr: "moi aussi", es: "yo también" },
  { fr: "moi non plus", es: "yo tampoco" },
  { fr: "qu’est-ce que c’est ?", es: "qué es esto" },
  { fr: "où est", es: "dónde está" },
  { fr: "combien ça coûte", es: "cuánto cuesta" },
  { fr: "je voudrais", es: "quisiera" },
  { fr: "je peux", es: "puedo" },
  { fr: "aide-moi", es: "ayúdame" },
  { fr: "regarde", es: "mira" },
  { fr: "écoute", es: "escucha" },
  { fr: "viens", es: "ven" },
  { fr: "attends", es: "espera" },
  { fr: "dis-moi", es: "dime" },
  { fr: "raconte", es: "cuéntame" },
  { fr: "je t’appelle", es: "te llamo" },
  { fr: "je t’écris", es: "te escribo" },
  { fr: "à bientôt", es: "hasta pronto" },
  { fr: "bonne journée", es: "buen día" },
  { fr: "bonne nuit", es: "buenas noches" },
  { fr: "santé (tchin)", es: "salud" },
  { fr: "félicitations", es: "felicidades" },
  { fr: "bonjour (très informel)", es: "hey" },
  { fr: "mec / pote", es: "tío" },
  { fr: "super / génial", es: "genial" },
  { fr: "cool", es: "guay" },
  { fr: "dingue", es: "loco" },
  { fr: "vrai", es: "verdad" },
  { fr: "mensonge", es: "mentira" },
  { fr: "histoire", es: "historia" },
  { fr: "souvenir", es: "recuerdo" },
  { fr: "rêve", es: "sueño" },
  { fr: "pluie", es: "lluvia" },
  { fr: "soleil", es: "sol" },
  { fr: "il fait beau", es: "hace buen tiempo" },
  { fr: "il pleut", es: "llueve" },
  { fr: "il fait chaud", es: "hace calor" },
  { fr: "il fait froid", es: "hace frío" },
  { fr: "vent", es: "viento" },
  { fr: "ciel", es: "cielo" },
  { fr: "terre", es: "tierra" },
  { fr: "feu", es: "fuego" },
  { fr: "chien", es: "perro" },
  { fr: "chat", es: "gato" },
  { fr: "animal", es: "animal" },
  { fr: "arbre", es: "árbol" },
  { fr: "fleur", es: "flor" },
  { fr: "rouge", es: "rojo" },
  { fr: "bleu", es: "azul" },
  { fr: "vert", es: "verde" },
  { fr: "jaune", es: "amarillo" },
  { fr: "noir", es: "negro" },
  { fr: "blanc", es: "blanco" },
  { fr: "gauche", es: "izquierda" },
  { fr: "droite", es: "derecha" },
  { fr: "tout droit", es: "todo recto" },
  { fr: "nord", es: "norte" },
  { fr: "sud", es: "sur" },
  { fr: "est (cardinal)", es: "este" },
  { fr: "ouest", es: "oeste" },
  { fr: "entrée", es: "entrada" },
  { fr: "sortie", es: "salida" },
  { fr: "ouvert (commerce)", es: "abierto" },
  { fr: "fermé (commerce)", es: "cerrado" },
  { fr: "toilettes", es: "aseos" },
  { fr: "wifi", es: "wifi" },
  { fr: "mot de passe", es: "contraseña" },
  { fr: "message", es: "mensaje" },
  { fr: "appel", es: "llamada" },
  { fr: "internet", es: "internet" },
  { fr: "ordinateur", es: "ordenador" },
  { fr: "clé", es: "llave" },
  { fr: "portefeuille", es: "cartera" },
  { fr: "sac", es: "bolsa" },
  { fr: "vêtements", es: "ropa" },
  { fr: "chaussures", es: "zapatos" },
  { fr: "pantalon", es: "pantalón" },
  { fr: "t-shirt", es: "camiseta" },
  { fr: "veste", es: "chaqueta" },
  { fr: "chapeau", es: "sombrero" },
  { fr: "lunettes", es: "gafas" },
  { fr: "montre", es: "reloj" },
  { fr: "papier", es: "papel" },
  { fr: "stylo", es: "bolígrafo" },
  { fr: "travail (job)", es: "empleo" },
  { fr: "patron", es: "jefe" },
  { fr: "collègue", es: "compañero" },
  { fr: "réunion", es: "reunión" },
  { fr: "vacances", es: "vacaciones" },
  { fr: "fête", es: "fiesta" },
  { fr: "anniversaire", es: "cumpleaños" },
  { fr: "cadeau", es: "regalo" },
  { fr: "musée", es: "museo" },
  { fr: "église", es: "iglesia" },
  { fr: "pont", es: "puente" },
  { fr: "lac", es: "lago" },
  { fr: "île", es: "isla" },
  { fr: "désert", es: "desierto" },
  { fr: "neige", es: "nieve" },
  { fr: "glace (froid)", es: "hielo" },
  { fr: "glace (dessert)", es: "helado" },
  { fr: "gâteau", es: "tarta" },
  { fr: "chocolat", es: "chocolate" },
  { fr: "jus", es: "zumo" },
  { fr: "thé", es: "té" },
  { fr: "soupe", es: "sopa" },
  { fr: "salade", es: "ensalada" },
  { fr: "poulet", es: "pollo" },
  { fr: "cochon / porc", es: "cerdo" },
  { fr: "vache", es: "vaca" },
  { fr: "huile", es: "aceite" },
  { fr: "beurre", es: "mantequilla" },
  { fr: "poivre", es: "pimienta" },
  { fr: "faim (j’ai)", es: "tengo hambre" },
  { fr: "soif (j’ai)", es: "tengo sed" },
  { fr: "j’ai sommeil", es: "tengo sueño" },
  { fr: "j’ai raison", es: "tengo razón" },
  { fr: "j’ai tort", es: "estoy equivocado" },
  { fr: "d’accord avec", es: "estoy de acuerdo" },
  { fr: "je suis perdu", es: "estoy perdido" },
  { fr: "je suis en retard", es: "llego tarde" },
  { fr: "je suis pressé", es: "tengo prisa" },
  { fr: "lentement", es: "despacio" },
  { fr: "vite", es: "rápido" },
  { fr: "ensemble", es: "juntos" },
  { fr: "seul (adv.)", es: "solo" },
  { fr: "peut-être (bis)", es: "a lo mejor" },
  { fr: "évidemment", es: "por supuesto" },
  { fr: "exactement", es: "exacto" },
  { fr: "parfait", es: "perfecto" },
  { fr: "incroyable", es: "increíble" },
  { fr: "dangereux", es: "peligroso" },
  { fr: "sûr / safe", es: "seguro" },
  { fr: "calme", es: "tranquilo" },
  { fr: "nerveux", es: "nervioso" },
  { fr: "content", es: "contento" },
  { fr: "en colère", es: "enfadado" },
  { fr: "surpris", es: "sorprendido" },
  { fr: "amoureux", es: "enamorado" },
  { fr: "marié", es: "casado" },
  { fr: "célibataire", es: "soltero" },
  { fr: "copain", es: "novio" },
  { fr: "copine", es: "novia" },
  { fr: "voisin", es: "vecino" },
  { fr: "invité", es: "invitado" },
  { fr: "étranger (personne)", es: "extranjero" },
  { fr: "touriste", es: "turista" },
  { fr: "guide", es: "guía" },
  { fr: "ticket", es: "entrada" },
  { fr: "réservation", es: "reserva" },
  { fr: "chambre double", es: "habitación doble" },
  { fr: "petit-déj inclus", es: "desayuno incluido" },
  { fr: "l’addition s’il te plaît", es: "la cuenta por favor" },
  { fr: "c’est trop cher", es: "es muy caro" },
  { fr: "c’est bon (goût)", es: "está rico" },
  { fr: "c’est délicieux", es: "está delicioso" },
  { fr: "sans gluten", es: "sin gluten" },
  { fr: "végétarien", es: "vegetariano" },
  { fr: "allergie", es: "alergia" },
  { fr: "médecin", es: "médico" },
  { fr: "pharmacie", es: "farmacia" },
  { fr: "médicament", es: "medicina" },
  { fr: "ordonnance", es: "receta" },
  { fr: "police", es: "policía" },
  { fr: "aide", es: "ayuda" },
  { fr: "danger", es: "peligro" },
  { fr: "feu (incendie)", es: "incendio" },
  { fr: "accident", es: "accidente" },
  { fr: "panne", es: "avería" },
  { fr: "réparation", es: "reparación" },
  { fr: "essence (station)", es: "gasolinera" },
  { fr: "parking", es: "aparcamiento" },
  { fr: "péage", es: "peaje" },
  { fr: "vitesse", es: "velocidad" },
  { fr: "feu rouge", es: "semáforo" },
  { fr: "priorité", es: "prioridad" },
  { fr: "gauche (tourner)", es: "gira a la izquierda" },
  { fr: "droite (tourner)", es: "gira a la derecha" },
  { fr: "arrêt", es: "parada" },
  { fr: "prochain", es: "próximo" },
  { fr: "dernier (bus)", es: "último" },
  { fr: "complet", es: "completo" },
  { fr: "libre (place)", es: "libre" },
  { fr: "fumeur", es: "fumador" },
  { fr: "non-fumeur", es: "no fumador" },
  { fr: "animaux", es: "mascotas" },
  { fr: "interdit", es: "prohibido" },
  { fr: "autorisé", es: "permitido" },
  { fr: "gratuit", es: "gratis" },
  { fr: "inclus", es: "incluido" },
  { fr: "supplément", es: "extra" },
  { fr: "réduction", es: "descuento" },
  { fr: "carte bancaire", es: "tarjeta" },
  { fr: "espèces", es: "efectivo" },
  { fr: "monnaie", es: "cambio" },
  { fr: "pourboire", es: "propina" },
  { fr: "facture", es: "factura" },
  { fr: "reçu", es: "recibo" },
  { fr: "impôt", es: "impuesto" },
  { fr: "travail (verbe déjà)", es: "currar" },
  { fr: "pause", es: "descanso" },
  { fr: "horaire", es: "horario" },
  { fr: "rendez-vous", es: "cita" },
  { fr: "retard", es: "retraso" },
  { fr: "annulé", es: "cancelado" },
  { fr: "complet (sold out)", es: "agotado" },
  { fr: "ouvert 24h", es: "abierto 24 horas" },
  { fr: "aujourd’hui même", es: "hoy mismo" },
  { fr: "cette nuit", es: "esta noche" },
  { fr: "cet après-midi", es: "esta tarde" },
  { fr: "ce matin", es: "esta mañana" },
  { fr: "la semaine prochaine", es: "la semana que viene" },
  { fr: "l’année dernière", es: "el año pasado" },
  { fr: "un jour", es: "un día" },
  { fr: "chaque jour", es: "cada día" },
  { fr: "tous les jours", es: "todos los días" },
  { fr: "souvent", es: "a menudo" },
  { fr: "rarement", es: "rara vez" },
  { fr: "soudain", es: "de repente" },
  { fr: "enfin", es: "por fin" },
  { fr: "au début", es: "al principio" },
  { fr: "à la fin", es: "al final" },
  { fr: "d’abord", es: "primero" },
  { fr: "ensuite (ordre)", es: "después" },
  { fr: "enfin (ordre)", es: "por último" },
  { fr: "par exemple", es: "por ejemplo" },
  { fr: "c’est-à-dire", es: "es decir" },
  { fr: "en fait", es: "de hecho" },
  { fr: "surtout", es: "sobre todo" },
  { fr: "au moins", es: "al menos" },
  { fr: "au plus", es: "como máximo" },
  { fr: "environ", es: "alrededor de" },
  { fr: "plus que", es: "más que" },
  { fr: "moins que", es: "menos que" },
  { fr: "autant que", es: "tanto como" },
  { fr: "si + adj", es: "tan" },
  { fr: "tellement", es: "tanto" },
  { fr: "quelque chose", es: "algo" },
  { fr: "quelqu’un", es: "alguien" },
  { fr: "quelque part", es: "en algún sitio" },
  { fr: "n’importe quoi", es: "cualquier cosa" },
  { fr: "personne (pronom nég.)", es: "nadie" },
  { fr: "nulle part", es: "en ningún sitio" },
  { fr: "chaque", es: "cada" },
  { fr: "plusieurs", es: "varios" },
  { fr: "aucun", es: "ninguno" },
  { fr: "les deux", es: "ambos" },
  { fr: "l’un l’autre", es: "el uno al otro" },
  { fr: "soi-même", es: "uno mismo" },
  { fr: "on (gens)", es: "se" },
  { fr: "il faut", es: "hay que" },
  { fr: "on peut", es: "se puede" },
  { fr: "ça va (affirmation)", es: "está bien" },
  { fr: "ça ne va pas", es: "no está bien" },
  { fr: "c’est parti", es: "vamos allá" },
  { fr: "on y est", es: "ya estamos" },
  { fr: "j’arrive", es: "ya llego" },
  { fr: "j’arrive pas", es: "no llego" },
  { fr: "laisse tomber", es: "déjalo" },
  { fr: "t’inquiète", es: "no te preocupes" },
  { fr: "calme-toi", es: "tranquilo" },
  { fr: "allez", es: "vamos" },
  { fr: "courage", es: "ánimo" },
  { fr: "bravo", es: "bien hecho" },
  { fr: "dommage", es: "qué pena" },
  { fr: "quelle horreur", es: "qué horror" },
  { fr: "quelle chance", es: "qué suerte" },
  { fr: "quel but", es: "qué gol" },
  { fr: "on a gagné", es: "ganamos" },
  { fr: "on a perdu", es: "perdimos" },
  { fr: "égalité", es: "empate" },
  { fr: "supporter", es: "aficionado" },
  { fr: "stade", es: "estadio" },
  { fr: "arbitre", es: "árbitro" },
  { fr: "hors-jeu", es: "fuera de juego" },
  { fr: "corner", es: "córner" },
  { fr: "penalty", es: "penalti" },
  { fr: "mi-temps", es: "descanso" },
  { fr: "seconde période", es: "segunda parte" },
  { fr: "champion", es: "campeón" },
  { fr: "coupe", es: "copa" },
  { fr: "ligue", es: "liga" },
  { fr: "classement", es: "clasificación" },
  { fr: "souvenir (objet)", es: "recuerdo" },
  { fr: "photo de voyage", es: "foto del viaje" },
  { fr: "couchage", es: "cama" },
  { fr: "tente", es: "tienda de campaña" },
  { fr: "camping", es: "camping" },
  { fr: "feu de camp", es: "hoguera" },
  { fr: "lever du soleil", es: "amanecer" },
  { fr: "coucher du soleil", es: "atardecer" },
  { fr: "étoile", es: "estrella" },
  { fr: "lune", es: "luna" },
  { fr: "ombre", es: "sombra" },
  { fr: "bruit", es: "ruido" },
  { fr: "silence", es: "silencio" },
  { fr: "voix", es: "voz" },
  { fr: "rire", es: "risa" },
  { fr: "pleurer", es: "llorar" },
  { fr: "sourire", es: "sonreír" },
  { fr: "embrasser", es: "besar" },
  { fr: "câlin", es: "abrazo" },
  { fr: "main (serrer)", es: "apretón" },
  { fr: "salut (geste)", es: "saludo" },
];

function keyOf(item) {
  return item.es.normalize("NFD").replace(/\p{Diacritic}/gu, "").toLowerCase().trim();
}

const seen = new Map();
for (const item of raw) {
  const k = keyOf(item);
  if (!seen.has(k)) seen.set(k, item);
}
const unique = [...seen.values()];
console.log("unique", unique.length, "raw", raw.length);
if (unique.length < 500) {
  console.error("NEED", 500 - unique.length, "more");
  process.exit(1);
}
const words = unique.slice(0, 500).map((item, i) => ({
  id: String(i + 1),
  fr: item.fr,
  es: String(item.es).replace(" (por la)", ""),
  ...(item.alt ? { alt: item.alt } : {}),
}));

const body = words
  .map((w) => {
    const alt = w.alt ? `, alt: ${JSON.stringify(w.alt)}` : "";
    return `  { id: "${w.id}", fr: ${JSON.stringify(w.fr)}, es: ${JSON.stringify(w.es)}${alt} }`;
  })
  .join(",\n");

const file = `export type Word500 = {
  id: string;
  fr: string;
  es: string;
  alt?: string[];
};

export const WORDS_500: Word500[] = [
${body},
];

export const WORD_COUNT = WORDS_500.length;
`;

fs.writeFileSync(path.join(__dirname, "../src/lib/words500.ts"), file);
console.log("wrote", words.length);
